### ISSUE TITLE
Questions: in which file is / are the access point/s configured

### ISSUE THREAD

**Issue by abysso2** [dreemurrs-embedded/Pine64-Arch#101]
Hi,
i am connected to my pinephone via ssh and i am wondering, which file i have to edit to delete a old access point entry?

Any hints?

Regards,
A.

**Comment by InFerYes** [comment]
How are the APs managed?

**Comment by abysso2** [comment]
The AP ist automatically added after installation, entering the sim pin and activating "mobile data". Its name is "Prepaid Contracts" and an AP from t-mobile is configured correctly.

But after the first reboot, This entry "Prepaid Contracts" is doubled and i can not delete one of them ...

**Comment by mogwa1** [comment]
It seems like it's related to the problem I had a while ago: #55 
I also got duplicate entries for the AP, and couldn't switch between APs from the settings menu.
I ended up manually editing the entry/entries in /etc/NetworkManager/system-connections

**Comment by abysso2** [comment]
Jupp, this is my issue .. i will edit  /etc/NetworkManager/system-connections.

THANK YOU!
