### ISSUE TITLE
Year 2115 Problem

### ISSUE THREAD

**Issue by grelltrier** [dreemurrs-embedded/Pine64-Arch#102]
Updating packages via 'pacman -Syu' fails due to the expired certificate

**Comment by Danct12** [comment]
The certificate is still valid for me, have you checked your time and date on the device?

**Comment by grelltrier** [comment]
Is it not 15 January, 2116? :D
![pineTime](https://user-images.githubusercontent.com/67273701/99939403-e27f4000-2d61-11eb-9511-96ebf830d942.jpeg)

Never mind then. I never bothered setting the time since I only use the phone to test applications on it. Its weird it changed itself like that though. It updated like a charm for the last weeks and I didn't change any of the time settings. Automatically updating the time does not seem to work for me

**Comment by grelltrier** [comment]
Apparently this has happened to people using Mobian too. According to the link the cause is still unknown but is likely to have something to do with the time synchronization.
https://wiki.mobian-project.org/doku.php?id=troubleshooting#year-2115-problem

**Comment by Danct12** [comment]
This should be fixed with this patch: https://patchwork.kernel.org/project/linux-arm-kernel/patch/20210515021439.55316-1-samuel@sholland.org

Which is also a part of the megi kernel.
