### ISSUE TITLE
danctnix-phosh-ui-meta meta package should be replaced with a package group

### ISSUE THREAD

**Issue by bobi32** [dreemurrs-embedded/Pine64-Arch#104]
Let’s start with some material to differentiate both alternatives: https://wiki.archlinux.org/index.php/Meta_package_and_package_group

Now to the point. As of now, danctnix-phosh-ui-meta, as a meta package, forces users to embrace the app selection it comes with, no matter how necessary each app is to Phosh to function.
More specifically, I was able to get my daily terminal emulator to run on my pinephone, and wanted to get rid of kgx since I don’t need it no more. Needless to say I was rather surprised to see that removing it would have yielded the removal of 95 other packages, some of them that cover key features of a regular smartphone experience.
As a point of comparison, in Arch, gnome & gnome-extra work as package groups instead of meta packages. This allows to finely tune which packages of both groups are installed and which aren’t.

As a side note, I suggest the “hide apps we don’t care” feature of danctnix-phosh-ui-meta should be taken out of the meta package and put in a dedicated package (which would be a dependency of the current meta package or a member of the package group).
The meta package should do nothing else than being a meta package, since at the moment, removing it while keeping all of its dependencies has side effects that a pure meta package should not have.

**Comment by Danct12** [comment]
This is no longer a issue for years now, and I have recently cleaned up the settings package for Phosh.
