### ISSUE TITLE
Ignore MicroSD and boot to eMMC

### ISSUE THREAD

**Issue by Jojonintendo** [dreemurrs-embedded/Pine64-Arch#113]
I can't figure out how to boot directly to eMMC, ignoring the MicroSD card that is inserted in the PinePhone. The µSD has been formatted and only serves as data folder, but somehow always gets chosen as boot medium when inserted. If I boot without the µSD, and then insert it, I can use it properly.

I've noticed that /boot/boot.txt does some checking whether a µSD card is present or not, but I don't know how it would be best modified to prevent this behavior. At least Mobian can ignore it properly, but I don't know if it performs some different checks.

I'll be happy to test suggestions and provide feedback, thanks in advance!

**Comment by Danct12** [comment]
Your SD card still has a valid boot0 and U-Boot header, there's **unfortunately no way I can bypass it** without modifying the A64's bootrom (if anyone knows better about sunxi please correct me)

[You can still remove the boot code from SD card](https://linux-sunxi.org/Bootable_SD_card#Cleaning)
