### ISSUE TITLE
pkg: gnome-clocks: Alarm with libfeedback (purism version) to vibrate

### ISSUE THREAD

**Issue by genofire** [dreemurrs-embedded/Pine64-Arch#115]
https://gitlab.gnome.org/GNOME/gnome-clocks/-/merge_requests/151

or

https://source.puri.sm/Librem5/debs/gnome-clocks/-/tree/pureos/v3.38.0-2pureos+librem5.3

**Comment by Danct12** [comment]
Already implemented in gnome-clocks-mobile package, this has been the default for at least one or two images now and I forgot this issue is still open.
