### ISSUE TITLE
pkg: mobile-config-firefox: update to latest version (2.0.0)

### ISSUE THREAD

**Issue by Valentin-Paramonov** [dreemurrs-embedded/Pine64-Arch#120]
Version 2.0.0 is available https://gitlab.com/postmarketOS/mobile-config-firefox/-/tags/2.0.0

**Comment by vfjpl** [comment]
@Danct12 any reason we are still using 1.0.0?

**Comment by Danct12** [comment]
@vfjpl We can't move to 2.0.0 yet as autoconfig for some reason does not work, I've been trying to troubleshooting it but so far no luck.

**Comment by Danct12** [comment]
Now it's 2.0.0.
