### ISSUE TITLE
Convergence Dock +Ethernet +Power (5V/2.1A): Arch Fails, Manjaro Works

### ISSUE THREAD

**Issue by DiagonalArg** [dreemurrs-embedded/Pine64-Arch#122]
This strikes me as a bit odd, and am wondering if there's something I can do to dig deeper into what might be going on here?

I'm on a pinephone (1.2b) with a convergence dock.  Arch updated to yesterday works with ethernet, but not with ethernet + power (5V/2.1A, not PD).  Oddly, that problem doesn't appear on Manjaro.  

If it makes any difference, both are the versions that I got off of the multiboot image.

**Comment by Danct12** [comment]
Please keep in mind that multiboot image is not supported and never will be. I'll look into this and see if this issue appears on latest release.
