### ISSUE TITLE
Chatty: unanswered telegram messages get duplicated after waking up from deep sleep

### ISSUE THREAD

**Issue by mkzmch** [dreemurrs-embedded/Pine64-Arch#128]
Here is how to reproduce this bug: 
1. Add a Telegram account in Chatty
2. Recieve a message through telegram
3. Do not answer the message
4. Wait for the phone to go into deep sleep mode
5. Unlock the phone and you will receive the message again
Sometimes the message gets duplicated 5-7min after waking up from deep sleep, sometimes instantly

**Comment by mkzmch** [comment]
The bug seems to be reproduced more reliably upon rebooting the device

**Comment by myxor** [comment]
It seems this is a bug in chatty. Please report it upstream to https://source.puri.sm/Librem5/chatty
