### ISSUE TITLE
Include Anbox patch for update RenderControl.cpp

### ISSUE THREAD

**Issue by Shatur95** [dreemurrs-embedded/Pine64-Arch#129]
Can we include https://github.com/anbox/anbox/pull/1678? This will allow to run more applications (for example, my banking apps require this).

**Comment by Danct12** [comment]
The patch doesn't work, so unless they update it and make it work please reopen.

https://github.com/anbox/anbox/issues/1637#issuecomment-737165854
https://github.com/anbox/anbox/pull/1678#issuecomment-737115400
