### ISSUE TITLE
Adopt modem-stack changes from Manjaro/PMOS

### ISSUE THREAD

**Issue by philmmanjaro** [dreemurrs-embedded/Pine64-Arch#132]
Currently there are a lot of changes going on on how to use the **eg25 modem**. I suggest to adopt the [current changes](https://gitlab.manjaro.org/manjaro-arm/issues/pinephone/phosh/-/issues/147) made.

- [x] [adjust kernel](https://gitlab.manjaro.org/manjaro-arm/packages/core/linux-pinephone) as needed
- [ ] [adjust ucm](https://gitlab.manjaro.org/manjaro-arm/packages/community/phosh/alsa-ucm-pinephone) as needed
- [x] [adjust eg25-manager](https://gitlab.manjaro.org/manjaro-arm/packages/community/phosh/eg25-manager) as needed
- [x] [adjust modemmanager](https://gitlab.manjaro.org/manjaro-arm/packages/community/phosh/modemmanager-pp) as needed

**Comment by Danct12** [comment]
Have done it forever ago, time to close.
