### ISSUE TITLE
Epiphany does not display any website

### ISSUE THREAD

**Issue by Barugon** [dreemurrs-embedded/Pine64-Arch#133]
I installed Epiphany on PinePhone but it won't display any website (or the most visited page either), just a blank window. When I navigate to a site, I can see, very briefly, the page squashed into the upper left quarter of the window and then it goes blank again.

Epiphany displays web pages just fine on other distributions.

**Comment by Ocawesome101** [comment]
I haven't tried regular Epiphany in a while, but `epiphany-mobile` seems to have this issue also.

**Comment by Danct12** [comment]
Maybe this is a mesa bug, I'll see if I can produce a apitrace and report it to upstream.

**Comment by Danct12** [comment]
I can confirm this is a mesa bug, downgrading back to mesa 20.3.4 fixed it.

https://gitlab.freedesktop.org/mesa/mesa/-/issues/4336

**Comment by Danct12** [comment]
Seems to have been fixed with latest mesa-git.
