### ISSUE TITLE
Request: ath9k kernel modules for atheros usb devices

### ISSUE THREAD

**Issue by pinoverclock** [dreemurrs-embedded/Pine64-Arch#134]
There is no dkms driver option for the atheros ath9k modules. Is there any chance to enable the build of the ath9k modules in the kernel?

>CONFIG_ATH9K_HW=m
>CONFIG_ATH9K_COMMON=m
>CONFIG_ATH9K=m
>CONFIG_ATH9K_AHB=m
>CONFIG_ATH9K_RATE_CONTROL=m
>CONFIG_ATH9K_HTC=m

**Comment by Danct12** [comment]
A part of kernel 5.10.19.
