### ISSUE TITLE
endless fmigrate_block messages on boot

### ISSUE THREAD

**Issue by hallyn** [dreemurrs-embedded/Pine64-Arch#136]
Trying archlinux-pinephone-phosh-20210214.img.xz on my braveheart pinephone.  On boot, I get an endless set of messages like

```
fmigrate_block: 561 Migrate node block (X) -> (y)
```

**Comment by Danct12** [comment]
This message is shown during disk resizing, please be patient and wait.

**Comment by hallyn** [comment]
Thanks - indeed I needed to be more patient.

(well, and be plugged in :)
