### ISSUE TITLE
SMS reception problem (Phosh)

### ISSUE THREAD

**Issue by lajonss** [dreemurrs-embedded/Pine64-Arch#137]
When the PinePhone is suspended receiving a SMS does wake it up - the screen lights up - but Chatty doesn't show any new messages. Subsequent messages are not received as well. Rebooting the device does help, but the unreceived messages are lost.

Downgrading modemmanager (and libmm-glib) to 1.14.8-3 resolves the issue (suggested by ThePosichronic on Discord).

edit
It seems that the "modem breaking update" resolves the issue.

**Comment by Danct12** [comment]
I'll be closing this issue due to the issue being resolved, feel free to reopen if the issue persists.
