### ISSUE TITLE
Not Booting without Battery Inserted

### ISSUE THREAD

**Issue by JonathanILevi** [dreemurrs-embedded/Pine64-Arch#144]
I have my PinePhone plugged-in, but the battery taken out.  When trying to boot it, it is stops the boot process showing the terminal output for a fraction of a second.  Interestingly, when I tried taking out the battery while the pohne is running, it did not shutdown.

I know wlan/bt and the modem are powered directly by the battery, and will not function.

I have the Ubuntu Touch Community Edition PinePhone, still with the original v1.1 board.  I am running Barebones, with sxmo-alarm.

**Comment by Danct12** [comment]
This seems to be done on purpose with megi kernel, @megous.
