### ISSUE TITLE
Kernel is misconfigured for NLS

### ISSUE THREAD

**Issue by patrakov** [dreemurrs-embedded/Pine64-Arch#146]
There is no way, in the current kernel configuration, to mount VFAT and CIFS filesystems with proper support for non-ASCII characters. Right now, on CIFS shares, characters outside of ISO-8859-1 show up as "???", and characters in ISO-8859-1 show up as garbage.

Please enable the following kernel options:

```
CONFIG_FAT_DEFAULT_UTF8=y
CONFIG_NLS_UTF8=y
CONFIG_NLS_DEFAULT="utf8"
```

**Comment by Danct12** [comment]
I have fixed this issue, please update your kernel and try again.

**Comment by patrakov** [comment]
Thanks, it works now.
