### ISSUE TITLE
Anbox not working with lxc 1:4.0.8-1

### ISSUE THREAD

**Issue by dariox86** [dreemurrs-embedded/Pine64-Arch#155]
Anbox crash upon launch with version 1:4.0.8-1 of lxc. As a workaround I downgraded lxc to version 1:4.0.6-1.

**Comment by Danct12** [comment]
Confirmed upstream issue, will downgrade package soon.

**Comment by dariox86** [comment]
Thank you.

**Comment by Danct12** [comment]
I'll close this issue for now, as this is upstream: https://github.com/anbox/anbox/issues/1801
