### ISSUE TITLE
[Phosh] Cannot enable bluetooth via Settings

### ISSUE THREAD

**Issue by lajonss** [dreemurrs-embedded/Pine64-Arch#163]
Workaround:
1. Enable bluetooth in Settings
2. ``systemctl restart bluetooth``

References:
- https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/332#note_1096941
- https://www.reddit.com/r/Fedora/comments/n0zniy/does_anyone_face_this_issue_with_bluetooth/gwa25x2/

Edit:
New workaround:
1. Don't open Settings
2. Use Phosh status bar BT toggle
3. Open Settings

**Comment by Danct12** [comment]
Seems to have fixed after upgrading to 3.38.6
