### ISSUE TITLE
After adding Nextcloud account successfully, the Nextcloud contacts are not shown in Contacts app

### ISSUE THREAD

**Issue by kingemir** [dreemurrs-embedded/Pine64-Arch#17]
I added a Nextcloud account successfully. While doing so, I granted access to my Nextcloud contacts. 

But in the Contacts app, they don't show up. There's only local contacts

**Comment by kingemir** [comment]
I re-did the whole process and now it works. I don't know why. I close the issue.

**Comment by ikidd** [comment]
I had the same thing, restarting after setting up NC account let me choose it in contacts.
