### ISSUE TITLE
Discord Link is invalid

### ISSUE THREAD

**Issue by RobertFULL30** [dreemurrs-embedded/Pine64-Arch#171]
This (phosh) is the best I've found for the Pinephone and I'd like to be able to contribute 

The discord link on https://danctnix.org is expired

Robert

**Comment by Danct12** [comment]
I have already removed the invalid link from the repository, but not on the website. Currently, there's no plan to reopen the Discord server yet.

**Comment by Danct12** [comment]
No plan to reopen the Discord server for now.

**Comment by RobertFULL30** [comment]
How about installing a version of discourse on https://danctnix.org 

I'm available to help, this build is the best I've found available and could use a more viable discussion platform IMO

There are still bugs but I can at least make calls and want to encourage and promote this.

**Comment by Danct12** [comment]
https://forum.pine64.org/forumdisplay.php?fid=159

There is also Matrix channel (#archmobile:kde.org) and Telegram (@archmobile) as replacement for Discord.
