### ISSUE TITLE
Anbox does not start with latest versions of lxc and boost-libs

### ISSUE THREAD

**Issue by dariox86** [dreemurrs-embedded/Pine64-Arch#173]
lxc and boost-libs must be kept at version 1:4.0.6-1 and 1.75.0-5 respectively for Anbox to work. I think no further information is needed since it should be fairly easy to reproduce.

**Comment by Danct12** [comment]
Fixed by rebuilding Anbox.

**Comment by dariox86** [comment]
I don't see an updated version of Anbox yet.
