### ISSUE TITLE
Request for package: kpeoplesink, for Plasma repository

### ISSUE THREAD

**Issue by SameExpert** [dreemurrs-embedded/Pine64-Arch#174]
In order to get Nextcloud contacts (from `kaccounts-providers`) showed on `plasmaphonedialer` and `plasma-phonebook`, [kpeoplesink](https://invent.kde.org/pim/kpeoplesink)  is required. A necessary **PKGBUILD** for this is required for **Plasma** repository.

**Comment by Danct12** [comment]
Hopefully kpeoplesink will have a tagged release soon: https://invent.kde.org/teams/plasma-mobile/issues/-/issues/40

**Comment by Danct12** [comment]
We already had kpeoplesink for long ago. This should now be closed: https://github.com/dreemurrs-embedded/Pine64-Arch/tree/master/PKGBUILDS/plasma/kpeoplesink
