### ISSUE TITLE
Chats/SMS won't start after 2021-06-23 update

### ISSUE THREAD

**Issue by aroggeband** [dreemurrs-embedded/Pine64-Arch#183]
This may be related to #181.

One of these is the culprit:
android-tools-31.0.0-4  
evolution-data-server-3.40.2-2  libcanberra-0.30+2+gc0620e4-5  
libldap-2.4.59-1  
**libphonenumber-8.12.25-1  
protobuf-3.17.3-1  
protobuf-c-1.4.0-1**  
raspberrypi-firmware-20210623-1
I suspect one of the highlighted ones.

**Comment by Danct12** [comment]
Already fixed https://github.com/dreemurrs-embedded/Pine64-Arch/commit/4183e1cf7597957ba6d9c2dac7bd0b4a3cca5e65
