### ISSUE TITLE
GNOME/Web (Epiphany) doesn't actually play youtube videos

### ISSUE THREAD

**Issue by godofgrunts** [dreemurrs-embedded/Pine64-Arch#19]
The release for the July 15 release says:

* Fixed YouTube playback on Epiphany

However, I'm still getting "Your browser does not currently recognize any of the video formats available.

I even tried reinstalling `gstreamer`gst-plugins-good` and `gst-plugins-bad` but to no avail.

**Comment by Danct12** [comment]
weird, seems to work for me just fine since that day i tested.

i'll check it out later when i got back home

**Comment by Danct12** [comment]
Was unable to produce the issue with the latest image..

![image](https://user-images.githubusercontent.com/19162768/88664262-065dac80-d107-11ea-9c10-43a6a9dc9d77.png)

**Comment by asriel-danctnix** [comment]
I was able to get it working by just installing gst-plugins-bad.

**Comment by ScardracS** [comment]
Yeah, gst is a must in order to make it working. If you try a clean build without it doesn't work

**Comment by Danct12** [comment]
Fixed by installing gst-plugins-bad, will be a part of next image.

Also, since Epiphany is deprecated, please check out mobile-config-firefox, you'll like it.
