### ISSUE TITLE
Keyboard layout can be difficult to get into in landscape mode

### ISSUE THREAD

**Issue by Ravlyx** [dreemurrs-embedded/Pine64-Arch#190]
This is my first issue ever reported, sorry in advance if it's not supposed to be here.

The Keyboard is central while in landscapemode.
It's hard to reach the t f g c v (maybe alt)) and a more relaxed layout would be appreciated.
There's enough 'unused' space to the left and right side.

**Comment by Danct12** [comment]
https://source.puri.sm/Librem5/squeekboard/-/issues

**Comment by Danct12** [comment]
Closing this old issue (I miss those days). squeekboard already had a landscape friendly layout for about a year now.
