### ISSUE TITLE
Autorotate not working in the newest update

### ISSUE THREAD

**Issue by SAPllak** [dreemurrs-embedded/Pine64-Arch#192]
Autorotate worked when I installed arch but when i updated it with (sudo pacman -Syu) and my autorotate sopped working. I hope this issue gets resolved.
![IMG20210712143953](https://user-images.githubusercontent.com/87317726/125297923-9a785200-e31f-11eb-9b85-eba572c06559.jpg)

**Comment by Danct12** [comment]
Seems like iio-sensor-proxy 3.1 is a bit buggy, this is what shows up in journalctl when it doesn't work:
```
Jul 12 15:02:05 danctnix iio-sensor-prox[3359]: driver_set_polling: assertion
```

However, there is a workaround to this: open the terminal and run `sudo systemctl restart iio-sensor-proxy`. I'll try to bisect this.

**Comment by Danct12** [comment]
Can also be related to #191.
