### ISSUE TITLE
Default `QT_WAYLAND_DISABLE_WINDOWDECORATION` should be set to `0`

### ISSUE THREAD

**Issue by tzcrawford** [dreemurrs-embedded/Pine64-Arch#197]
[See this gitlab issue I made on the purism gitlab page.](https://source.puri.sm/Librem5/phoc/-/issues/221)

The problem is that windows using qt will by default spawn without window border and thus windows in convergence mode cannot be easily resized. Then again, disabling this could be considered to waste screen space when using only the phone screen. Apparently PureOS has this set to `0`.

**Comment by Danct12** [comment]
d96f64fb757bbf3d2ab414ae74d20d6814b13920
