### ISSUE TITLE
pine64 corrupted .db file

### ISSUE THREAD

**Issue by ejiek** [dreemurrs-embedded/Pine64-Arch#2]
Due to `pine64` being defined as `http` repo, my `/var/lib/pacman/sync/pine64.db` got populated by some html page (cellular provider redirect or https redirect in the repo itself).
It resulted in following error during pacman update:
```
error: could not open file /var/lib/pacman/sync/pine64.db: Unrecognized archive format
error: failed to prepare transaction (invalid or corrupted database)
```

I had to modify `http` to `https` for `pine64` repo in `/etc/pacman.conf` and delete `/var/lib/pacman/sync/pine64.db`.
After this updates started to work like a charm.

Second thing is SigLevel which set to `Never`.
I don't think it's a good combination with `http`.

I haven't found where to patch it in this repo so I ask you to update it for the next release if you don't mind =]

**Comment by Danct12** [comment]
I'll think of signing the packages in next release, right now we're preparing to push Phosh UI packages.

**Comment by Danct12** [comment]
I've solved the https issue with the latest installations.

Still hasn't signed packages yet.

**Comment by Danct12** [comment]
Issue solved with the latest image.

**Comment by kescherCode** [comment]
Hmmm... I found that the current images have "SigLevel = Never" in some of the repos, and that the packages don't actually have signatures (.sig files).
So the packages aren't signed.
