### ISSUE TITLE
No Cellular Data: cdc-wdm0 says disconnected.

### ISSUE THREAD

**Issue by d0n601** [dreemurrs-embedded/Pine64-Arch#200]
There is no cellular data available, my configuration is the same as it is on Manjaro which works well with AT&T data.  The phone's 4G connection is fine, I can send/recieve calls and SMS messages, just no data.

`nmcli d` gives the output that `cdc-wdm0 gsm disconnected`

If I issue `sudo nmcli d connect cdc-wdm0` it returns `Error: Connection activation failed: (1) Unkown error.`

Also an interesting note, toggling the wifi on and off also seems to cause the modem to cut out entirely, it does appear to come back though after some time.

I'm running the OS with Phosh off of a microSD card with FDE. The packages are all updated. This is a Manjaro community edition phone.

**Comment by nephitejnf** [comment]
On getting data, you can do it, you just need to tweak the settings for the APN name, I had to set it to "phone" in all lowercase, then after that data worked fine.
