### ISSUE TITLE
the custom modem firmware doesn't work at all 

### ISSUE THREAD

**Issue by Idcrafter** [dreemurrs-embedded/Pine64-Arch#201]
i have the newest version of the modem and arch plasma mobile image flashed and it can't use the cellular network and in the settings software does it not even show any information on the modem at all 
![Screenshot_20210713_000437](https://user-images.githubusercontent.com/50270538/128569526-00374ace-7614-4825-b341-34aea48503b9.png)

**Comment by Danct12** [comment]
I have never tried out the CFW, so I need `journalctl -b`

**Comment by Danct12** [comment]
Closing due to lack of information.
