### ISSUE TITLE
Both wired & wireless internet disappeared after upgrade to kernel 5.12.19 (barebones).

### ISSUE THREAD

**Issue by latgarf** [dreemurrs-embedded/Pine64-Arch#203]
ip a
shows only these interfaces:
1: lo
2: usb0

ping 8.8.8.8
ping: socket: Address family not supported by protocol
ping: connect: Network is unreachable

Same output when WiFi hardware switch is turned off - like the system doesn't see WiFi card at all.

I observe the same problem on my other install with kernel 5.13.7-2-danctnix.
It's now looking more like a hardware issue, but I didn't see any reason for it to arise, hence suspected kernel upgrade as a culprit.

**Comment by Danct12** [comment]
Can you check lsmod and see if modules are loaded?

**Comment by latgarf** [comment]
sun4i_lradc_keys  is the only loaded module.

**Comment by Danct12** [comment]
That's weird, can you try `modprobe 8723cs` and see if it loads the wifi module? You can also try to reinstall the kernel if that doesn't help.

**Comment by latgarf** [comment]
```
# modprobe 8723cs
modprobe: FATAL: Module 8723cs not found in directory /lib/modules/5.12.19-1-danctnix
```

**Comment by Danct12** [comment]
Huh, that seems like the kernel hasn't fully updated, can you check if /boot is mounted on your device? You may have a broken fstab.

**Comment by latgarf** [comment]
`/dev/mmcblk0p2  is mounted at  /boot`

**Comment by Danct12** [comment]
What's in it? Usually we keep rootfs at p2 and boot at p1. Also, can you post the output of /etc/fstab?

**Comment by latgarf** [comment]
```
# cat /etc/fstab
# /dev/loop0p2
UUID=...   / ext4  rw,relatime  0 1

# /dev/loop0p1
UUID=...   /boot vfat rw,relatime...,errors=remount-ro  0 2
```

**Comment by Danct12** [comment]
Try to reinstall your kernel then (pacman -S linux-pine64) and reboot, see if that fixes it.

**Comment by latgarf** [comment]
What's the command to reinstall kernel, please?
Is this expected to work without internet connection?

**Comment by Danct12** [comment]
Download this and transfer it to your device https://p64.arikawa-hi.me/pine64/aarch64/linux-pine64-5.13.8-1-aarch64.pkg.tar.xz

Then run `pacman -U linux-pine64-5.13.8-1-aarch64.pkg.tar.xz`

**Comment by latgarf** [comment]
Installed, rebooted - now there's wifi :)  Thanks!  I'll try to upgrade now pacman -Syu.  I guess the initial problem was because of power failure during kernel upgrade...

**Comment by Danct12** [comment]
Yes, please try to avoid that.
