### ISSUE TITLE
[PineTab] Build with USB module support

### ISSUE THREAD

**Issue by danielbarry** [dreemurrs-embedded/Pine64-Arch#213]
I'm trying to get a USB WiFi dongle to work (the RTL8192) but it does not, yet it works with all other mainline kernels.

I was pointed towards this line in the configuration is disabled, as well as pretty much every other device you might want to plug in: https://github.com/dreemurrs-embedded/Pine64-Arch/blob/master/PKGBUILDS/pine64/linux-pine64/config#L1903

The PineTab has a USB port and it would be great to use it for stuff. Can you enable the kernel modules in the builds please?

These have been set in Manjaro for example: https://gitlab.manjaro.org/manjaro-arm/packages/core/linux/-/blob/master/config#L3390

**Comment by Danct12** [comment]
c211b681087ee30307fb794f672c14b464317337

**Comment by danielbarry** [comment]
Thanks @Danct12 :)
