### ISSUE TITLE
Enable wireless extensions compatibility layer in the kernel

### ISSUE THREAD

**Issue by al95** [dreemurrs-embedded/Pine64-Arch#215]
Hi.
There are tools still around that rely on the old and deprecated wireless extensions to interact with wifi interfaces.
These tools currently don't work on the pinephone since almost all wireless drivers are using the new cfg80211 APIs.
There is however a compatibility layer in the kernel that translates the old wireless extensions ioctls to cfg80211 functions.
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/net/wireless/wext-compat.c

This is disabled in the current kernel config, so I suggest enabling it to increase compatibility.
The flag is "CONFIG_CFG80211_WEXT".
https://github.com/dreemurrs-embedded/Pine64-Arch/blob/55367dfec355a4ce2db545254ef63bf3b5ba7d21/PKGBUILDS/pine64/linux-pine64/config#L1369

It's also enabled on both desktop and ARM Arch.
https://github.com/archlinux/svntogit-packages/blob/c2f783098f22cc0b7ae38bebd5a65a4480439804/trunk/config#L2026
https://archlinuxarm.org/packages/aarch64/linux-aarch64/files/config

**Comment by Danct12** [comment]
Thanks! 4f236e3c92b104fbeb9d9eed5074993bc2e47e24
