### ISSUE TITLE
Sound not working after update

### ISSUE THREAD

**Issue by dariox86** [dreemurrs-embedded/Pine64-Arch#216]
In sound settings it reads "Dummy output" instead of the actual speaker. Downgrading linux-pine64 and alsa-ucm-pinephone to 5.13.14-2 and 0.4-1 respectively fixes the issue.

**Comment by Danct12** [comment]
Working fine under 5.14.1-1 and 0.5.0-1.

**Comment by dariox86** [comment]
Now it works. Thank you.
