### ISSUE TITLE
Downgrade Kirigami to fix bugs in Plasma Mobile

### ISSUE THREAD

**Issue by AngelTomkins** [dreemurrs-embedded/Pine64-Arch#221]
With Plasma Mobile, there was an update to Kirigami(from 85 to 86) which broke many visual indicators such as sliders, check boxes, radio buttons, etc. The issue is upstream since it has been seen in Postmarket OS. 

The short term solution is to downgrade Kirigami back to 85 to get functionality to return.

**Comment by bhush9** [comment]
Or upgrade qqc2 breeze style I think also should do it.

**Comment by Danct12** [comment]
Thanks, I've fixed this with e950de1bda69b949e3ed981b080b0f4b4b4db554
