### ISSUE TITLE
Matrix Group Doesn't Exist?

### ISSUE THREAD

**Issue by ragreenburg** [dreemurrs-embedded/Pine64-Arch#222]
Looking up the matrix group gives back no results.

![image](https://user-images.githubusercontent.com/24358100/134387841-a1ff56fe-502a-4f7a-b32c-1460014d9123.png)

**Comment by Danct12** [comment]
Have you tried to join it anyway? There's a join button next to the input box.

**Comment by ragreenburg** [comment]
Shoot, sorry. I didn't even see that button, I'm new to Matrix haha. It worked!
