### ISSUE TITLE
Firefox breaks update

### ISSUE THREAD

**Issue by ragreenburg** [dreemurrs-embedded/Pine64-Arch#224]
I just downloaded the most recent installer and went to update but the update doesn't complete because it can't find the Firefox tar package.

**Comment by Danct12** [comment]
Which package that it can't find exactly? We only maintain a few repository that are essential to the phone, others are from upstream Arch Linux ARM project.

**Comment by ragreenburg** [comment]
It looks like it was Firefox 92(?), either way I realize now that it is upstream.
