### ISSUE TITLE
Waydroid does not show up since yesterday morning

### ISSUE THREAD

**Issue by dariox86** [dreemurrs-embedded/Pine64-Arch#231]
- Device: PinePhone
- Kernel Version : 5.14.14-1-danctnix
- UI: Phosh

### Steps to reproduce
Install archlinux-pinephone-phosh-20211022.img.xz on the PinePhone, perform an update with Pacman, install Waydroid following instructions in the wiki and launch Waydroid.

### Expected behavior
Waydroid should eventually show up.

### Actual behavior
Waydroid does not show up. "$ waydroid log" throws an infinite bunch of "Failed to get service waydroidplatform, trying again..."

It has stopped working since yesterday morning. I performed an update shortly before it stopped working. I reverted the update to no avail. Maybe I did not revert every package. I am not sure, I am unable to provide further information because I reinstalled the operating system from scratch since then. No further information should be needed because it should be fairly easy to reproduce.

**Comment by xsaliniere** [comment]
Same here unfortunately.

**Comment by Danct12** [comment]
Sounds like upstream issue, I suggest joining the discussion here: https://github.com/waydroid/waydroid/issues/180

I'll be reverting back to waydroid 1.1.1 (4c0a4359136a2093bf3be31385f25746fe1e44b1) in the meantime.
