### ISSUE TITLE
More polish

### ISSUE THREAD

**Issue by julianfairfax** [dreemurrs-embedded/Pine64-Arch#235]
First off, I'd like to thank you for maintaining this OS as I believe Linux phones are the future despite their current issues, of which one of them I believe to be a fragmented ecosystem. There are many OSes for Linux phones with most of them having contributed something to most of the others. This is great from a development standpoint but not great from a user experience standpoint. 

The good thing is that most of the time this isn't really noticed, but in some cases it is quite obvious that different components from different developers are all being used in the same OS such as the green enter key in odk-sdl keyboard from postmarketOS or the green toggles in the tweaks app from postmarketOS. Both of these use the postmarketOS accent color, whose shade of green is only ever seen there in the OS, and is generally replaced by GNOME's blue accent color everywhere else.

Of course this is a small issue in this case, and other cases exist such as King's Cross, Megapixels, and Portfolio from independent developers, but they do a better job of fitting in even though their developers aren't directly involved in this project either. I'm not suggesting that upstream developers don't tailor their components for their own OS, that each OS develop their own, or that one centralized entity take charge of all development, but rather that the distributor of the final OS, in this case you, tailor the components to match your final OS. 

For example, my suggestion here would be to use the GNOME accent color for the odk-sdl keyboard enter key and the tweaks app icon toggles. These might be small changes, even useless changes, but in my personal opinion at least, they'd make the OS more appealing by eliminating what are small distractions from an otherwise seamless and functional OS. Again, thanks for making this, and any thoughts on this issue or changes for it are welcome.

**Comment by julianfairfax** [comment]
A new logo would also be nice, something more simple than this one. There's just a bit too much going on in it for it be recognizable and easy on the eyes. For parity with the desktop it should also not show during boot, but this makes some sense on a mobile phone.

**Comment by julianfairfax** [comment]
If anyone wants to do all these things manually you can run these commands:
```
sudo sed -i 's/003C00/3584E4/' /etc/osk.conf 
sudo mkinitcpio -P
sudo curl -L -s -o /usr/share/icons/hicolor/scalable/apps/org.danctnix.Tweaks.svg https://gitlab.gnome.org/GNOME/gnome-tweaks/-/raw/master/data/org.gnome.tweaks.svg
sudo sed -i 's/quiet\ bootsplash\.bootfile\=bootsplash\-themes\/danctnix\/bootsplash//' /boot/boot.txt
cd /boot
sudo ./mkscr 
```
You'll have to rerun them when something is upgraded, and of course you could just build the packages yourself instead of doing this or changing the upstream, but it would be a welcome change in my opinion if things were more polished by default.

**Comment by julianfairfax** [comment]
Posting this here as an idea for a better icon. Inspired by the icon of the Mobian Matrix room which I found to have beauty in it's simplicity. I can send over the project file if you want but it's not difficult to replicate
![mobot1](https://user-images.githubusercontent.com/43753131/140621717-ab7ad332-2bde-442e-bc6c-9a9196af85ab.png)
.

**Comment by 1peter10** [comment]
I read the initial post (please consider using paragraphs for readability) yesterday, and took some time to think about it:

- regarding postmarketOS/DanctNIX Tweaks: I don't find the green that disturbing, and since GNOME Tweaks has also been gotten some libhandy "treatment" (sadly it's still to wide), I am against changing the icon to the one of GNOME Tweaks - otherwise people that have both installed would end up with to identical icons named Tweaks, that are different apps and have different features.
- OSK-SDL: Really? How often do you reboot your phone? [Purism have themed OSK-SDL](https://source.puri.sm/librem5-apps/osk-sdl/-/merge_requests/9) to match Squeekboard better, so the hard work is done.

I recommend trying to change the relevant PKGBUILD scripts and creating pull requests so that Danct12 has an easier time if he wants to apply these changes.

**Comment by julianfairfax** [comment]
> I read the initial post (please consider using paragraphs for readability) yesterday, and took some time to think about it:
> 
There are now paragraphs
>     * regarding postmarketOS/DanctNIX Tweaks: I don't find the green that disturbing, and since GNOME Tweaks has also been gotten some libhandy "treatment" (sadly it's still to wide), I am against changing the icon to the one of GNOME Tweaks - otherwise people that have both installed would end up with to identical icons named Tweaks, that are different apps and have different features.
> 

Well they could also have all three installed, but realistically it's going to be the one best supported: danctnix's
>     * OSK-SDL: Really? How often do you reboot your phone? [Purism have themed OSK-SDL](https://source.puri.sm/librem5-apps/osk-sdl/-/merge_requests/9) to match Squeekboard better, so the hard work is done.
> 
> 

Quite often actually, this is a development device after all. And the hard work is changing one config file.
> I recommend trying to change the relevant PKGBUILD scripts and creating pull requests so that Danct12 has an easier time if he wants to apply these changes.

I already made a pull request for danctnix tweaks and will make one here for osk-sdl if I get a positive response from them here.

**Comment by Danct12** [comment]
Regarding DanctNIX Tweaks, I'll get rid of it when pmOS tweaks becomes distro-agnostic - upstream issue: https://gitlab.com/postmarketOS/postmarketos-tweaks/-/issues/12

**Comment by julianfairfax** [comment]
I suppose that goes for osk-sdl too with this upstream issue I opened: https://gitlab.com/postmarketOS/osk-sdl/-/issues/137

**Comment by julianfairfax** [comment]
Regarding logos, here's an updated proposition for the Matrix room, still inspired by Mobian:
![mobot2](https://user-images.githubusercontent.com/43753131/140636992-86e361ab-bfae-4ffc-ab60-9fd90a34c53d.png)

This wouldn't work during boot so I have a proposition for that, inspired by Arch Linux ARM:
![Arch_Linux_ARM_logo](https://user-images.githubusercontent.com/43753131/140637084-1001fa4a-b9a1-4de0-9b4d-7bf1d7b23733.png)

In case you noticed, that one wouldn't work on boot either, so the actual proposition has a different colour for the text. I've attached it here:
https://user-images.githubusercontent.com/43753131/140637055-cfe61aa0-dd5a-4529-ae86-a472c82c0221.png

**Comment by julianfairfax** [comment]
@Danct12 Should I open a separate issue or a pull request for the branding changes or do you not any changes to be made? Cause this issue is closed apart from that, which could be considered a separate issue and which you haven't yet commented on. I suggest you consider branding changes as the logo is literally the first thing you see when you turn on the phone and the last thing you see what it turns off, and I believe that Mobian has excelled at this branding, hence my inspiration for the Matrix room logo. Their boot screen logo is also similar to my second proposition, in the way that it's just text, but this one is obviously from the Arch Linux ARM logo. I believe a good brand is important as it makes the experience feel more professional. If you have conflicting views, please close this issue.

**Comment by mossymossmoss** [comment]
I created an issue to talk about a logo change (#314) without seeing that this issue existed. Here are some mock-ups of possible logos that I made with variants that include a phone camera bar

![Danctnix1](https://user-images.githubusercontent.com/56167669/154110789-5c92a985-ec50-4d70-a37c-5f1dc84447cc.svg)
![Danctnix2](https://user-images.githubusercontent.com/56167669/154110809-924f2633-5c37-4bcb-8b17-985a7a2aa017.svg)
![Danctnix2Notch](https://user-images.githubusercontent.com/56167669/154110811-4b91365d-45ed-4e1d-abd6-13f772b51b0a.svg)
![Danctnix1Notch](https://user-images.githubusercontent.com/56167669/154110806-9fe4ed39-7f7d-4881-ae46-b37fe8182be4.svg)

**Comment by julianfairfax** [comment]
> I created an issue to talk about a logo change (#314) without seeing that this issue existed. Here are some mock-ups of possible logos that I made with variants that include a phone camera bar
> 
> ![Danctnix1](https://user-images.githubusercontent.com/56167669/154110789-5c92a985-ec50-4d70-a37c-5f1dc84447cc.svg)
> ![Danctnix2](https://user-images.githubusercontent.com/56167669/154110809-924f2633-5c37-4bcb-8b17-985a7a2aa017.svg)
> ![Danctnix2Notch](https://user-images.githubusercontent.com/56167669/154110811-4b91365d-45ed-4e1d-abd6-13f772b51b0a.svg)
> ![Danctnix1Notch](https://user-images.githubusercontent.com/56167669/154110806-9fe4ed39-7f7d-4881-ae46-b37fe8182be4.svg)

Those actually really nice!
