### ISSUE TITLE
SMS unstable on Danish sim-card

### ISSUE THREAD

**Issue by johays** [dreemurrs-embedded/Pine64-Arch#244]
- Device: PinePhone
- Kernel Version : 5.15.2-1-danctnix
- UI: Phosh 0.14.0-1

Chatty (v 0.4.0-1) unable to send sms on Danish number. A week ago it was working fine. For a week it has been impossible to get messages through. SIM-card has been tested on another phone and is working fine.
Both without contry-cocde and with +45 and 0045 contry codes have been tried, with no positive result.

### Steps to reproduce
Reproduce by sending SMS from a Danish sim-card. 

### Expected behavior
That messages are send, received by the recipient and that delivery-reports gets back to Chatty.

### Actual behavior
Messages are not send and an error is represented by a small red cross. 

### Logfiles and additional information
(please direct me to relevant logfiles and/or debug-info, and I will happily provide it)

_(edit: moved a line from " steps to reproduce" to the intro-text)_

**Comment by johays** [comment]
(Relating to [this bug in chatty](https://source.puri.sm/Librem5/chatty/-/issues/505), I have tried forcing 2G and 3G, but it doesn't seem to resolve the issue)

**Comment by Danct12** [comment]
It seems like both G and alexela from the chat has also reported the same issue. It looks like removing the battery, wait for a bit and put it back in fixed the issue.. very weird one. Can you give it a shot?

**Comment by Danct12** [comment]
Closing as this issue has been inactive for ~2 years, as well as lack of response from the reporter. If this is still an issue, please open a new bug report.
