### ISSUE TITLE
systemd-networkd vs NetworkManager

### ISSUE THREAD

**Issue by 3nprob** [dreemurrs-embedded/Pine64-Arch#248]
I would be curious to hear if there's any story behind the choice of going with NetworkManager.

Personally I find systemd-networkd more lightweight, flexible, robust than NM. IMO it's a lot more obvious default.

At least I'd like to raise the question and see if some discussion comes out of it.

**Comment by Danct12** [comment]
Use the forum for discussion: https://forum.pine64.org/forumdisplay.php?fid=159

**Comment by 3nprob** [comment]
brainfarted there and didn't consider that's actually just the place for it. thanks for redirecting
