### ISSUE TITLE
Does the 20211129 image have Megi's latest crust improvements ?

### ISSUE THREAD

**Issue by lafleurdeboum** [dreemurrs-embedded/Pine64-Arch#249]
- Device: PinePhone

I couldn't find any mention of "crust" in the changelog ; I'm aware that developer Megi greatly improved battery life when idle by enhancing crust support, as mentioned [here](https://liliputing.com/2021/05/megis-pinephone-kernel-updates-bring-battery-life-performance-improvements.html). Do you include those improvements in the pinephone's latest Arch image ? I'd rather use plain Arch than Manjaro, since it's my main OS at home.

### Expected behavior
Have a mention of the crust enhanced support somewhere in this repository.

### Actual behavior
Searching "crust" in this repository only returns the details of a PKGBUILD that doesn't explicitely mention enhanced battery life.

I post this issue in the hope that it helps future users of this repo to figure an answer to this (arguably) pretty strategic concern. I sincerely hope you will find it constructive.

**Comment by Danct12** [comment]
The article you linked is from May, we already had crust support for a long time now.
