### ISSUE TITLE
Feature Request: Boot from eMMC with SD card inserted

### ISSUE THREAD

**Issue by ned7000** [dreemurrs-embedded/Pine64-Arch#253]
- Device: PinePhone (Nov 2021 model), 3GB RAM, 32GB eMMC
- Kernel Version : $5.16.0-rc2-2-danctnix
- UI: SXMO

When I insert a blank SD card, the PinePhone will not boot from eMMC.
Is there some way to set a file on the SD card to point to the boot partition on the eMMC?

**Comment by Danct12** [comment]
You still have U-Boot on SD card. https://linux-sunxi.org/Bootable_SD_card#Cleaning
