### ISSUE TITLE
No audio/microphone capabilities

### ISSUE THREAD

**Issue by fbmoose48** [dreemurrs-embedded/Pine64-Arch#255]
- Device: PinePhone Pro
- Kernel Version :  5.16.0-rc3-1
- UI: phosh

### Steps to reproduce
place/answer a call, play video in firefox

### Expected behavior
audio playback, microphone input

### Actual behavior
can'y hear or be heard on calls (both regular and speaker), no audio playback in browser.

"Sound" in settings indicates "Speaker" as output device. testing speakers gets no output. Playing audio in browswer gets nooutput, although the bar underneath does move as though it is detecting audio to output.

"Sound" in settings indicates "Analog Input" as input device. Not able to be heard on calls. "Sound Recorder" records a flat line with no sound when played back.

### Logfiles and additional information
`alarm@danctnix ~]$ journalctl | grep callaudiod`
`Dec 10 14:40:13 danctnix audit[3409]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 subj==unconfined pid=3409 comm="callaudiod" exe="/usr/bin/callaudiod" sig=11 res=1`
`Dec 10 14:40:13 danctnix kernel: audit: type=1701 audit(1639165213.733:826): auid=1000 uid=1000 gid=1000 ses=2 subj==unconfined pid=3409 comm="callaudiod" exe="/usr/bin/callaudiod" sig=11 res=1`
`Dec 10 14:40:38 danctnix systemd-coredump[142893]: Process 3409 (callaudiod) of user 1000 dumped core.`
`                                                   Found module callaudiod with build-id: c0a532b2251beabf5437c88cd8214e5e36bff9dd`
`                                                   #1  0x0000aaaac6ef6ba0 n/a (callaudiod + 0x6ba0)`
`                                                   #14 0x0000aaaac6ef30d4 main (callaudiod + 0x30d4)`
`                                                   #16 0x0000aaaac6ef3130 n/a (callaudiod + 0x3130)`
`                                                   #17 0x0000aaaac6ef3130 n/a (callaudiod + 0x3130)`
`Dec 10 14:48:01 danctnix audit[142908]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 subj==unconfined pid=142908 comm="callaudiod" exe="/usr/bin/callaudiod" sig=11 res=1`
`Dec 10 14:48:01 danctnix kernel: audit: type=1701 audit(1639165681.503:849): auid=1000 uid=1000 gid=1000 ses=2 subj==unconfined pid=142908 comm="callaudiod" exe="/usr/bin/callaudiod" sig=11 res=1`
`Dec 10 14:48:03 danctnix systemd-coredump[143019]: Process 142908 (callaudiod) of user 1000 dumped core.`
`                                                   Found module callaudiod with build-id: c0a532b2251beabf5437c88cd8214e5e36bff9dd`
`                                                   #1  0x0000aaaad0836ba0 n/a (callaudiod + 0x6ba0)`
`                                                   #14 0x0000aaaad08330d4 main (callaudiod + 0x30d4)`
`                                                   #16 0x0000aaaad0833130 n/a (callaudiod + 0x3130)`
`                                                   #17 0x0000aaaad0833130 n/a (callaudiod + 0x3130)`

`[alarm@danctnix ~]$ journalctl | grep calls`
`Dec 09 23:59:00 danctnix dbus-daemon[3264]: [session uid=1000 pid=3264] Activating via systemd: service name='org.bluez.obex' unit='dbus-org.bluez.obex.service' requested by ':1.54' (uid=1000 pid=3541 comm="gnome-calls --daemon ")`
`Dec 10 00:41:40 danctnix dbus-daemon[3269]: [session uid=1000 pid=3269] Activating via systemd: service name='org.bluez.obex' unit='dbus-org.bluez.obex.service' requested by ':1.54' (uid=1000 pid=3551 comm="gnome-calls --daemon ")`
`Dec 10 13:34:02 danctnix gnome-calls[5799]: cannot open display: :0`
`Dec 10 13:34:29 danctnix dbus-daemon[3305]: [session uid=1000 pid=3305] Activating via systemd: service name='org.bluez.obex' unit='dbus-org.bluez.obex.service' requested by ':1.52' (uid=1000 pid=3642 comm="gnome-calls --daemon ")`
`Dec 10 14:40:38 danctnix gnome-calls[3642]: Couldn't enable speaker: Timeout was reached`
`Dec 10 14:40:38 danctnix gnome-calls[3642]: Failed to enable speaker: Timeout was reached`
`Dec 10 14:40:39 danctnix gnome-calls[3642]: Couldn't enable speaker: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`
`Dec 10 14:40:39 danctnix gnome-calls[3642]: Failed to disable speaker: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`
`Dec 10 14:40:39 danctnix dbus-daemon[3305]: [session uid=1000 pid=3305] Activating service name='org.mobian_project.CallAudio' requested by ':1.52' (uid=1000 pid=3642 comm="gnome-calls --daemon ")`
`Dec 10 14:41:04 danctnix gnome-calls[3642]: Couldn't enable speaker: Timeout was reached`
`Dec 10 14:41:04 danctnix gnome-calls[3642]: Failed to enable speaker: Timeout was reached`
`Dec 10 14:41:04 danctnix gnome-calls[3642]: Error hanging up ModemManager call to +1XXXXXXXXXXX': GDBus.Error:org.freedesktop.ModemManager1.Error.Core.Failed: This call was not active, cannot hangup`
`Dec 10 14:48:03 danctnix gnome-calls[3642]: Couldn't enable speaker: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`
`Dec 10 14:48:03 danctnix gnome-calls[3642]: Failed to enable speaker: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying`
`Dec 10 14:48:06 danctnix dbus-daemon[3305]: [session uid=1000 pid=3305] Activating service name='org.mobian_project.CallAudio' requested by ':1.52' (uid=1000 pid=3642 comm="gnome-calls --daemon ")`

**Comment by bjadel** [comment]
Same here. Do you need more information?

**Comment by fbmoose48** [comment]
I'm happy to post more logs if that helps, just need some direction in what you'd even need.

I understand Mobian has a working config at
https://gitlab.com/mobian1/packages/alsa-ucm-conf/-/blob/mobian/debian/patches/0005-ucm2-add-PinePhone-Pro-configuration.patch

**Comment by Danct12** [comment]
Audio is heavily a WIP now, that UCM works, but you will not be able to get any callaudio from it now.

**Comment by Danct12** [comment]
`alsa-ucm-pinephonepro` has been added.

**Comment by fbmoose48** [comment]
Soundrecorder and audio playback works, do calls work as well? I can test calls out with a SIM  switch if that's unknown

**Comment by bjadel** [comment]
> Soundrecorder and audio playback works, do calls work as well? I can test calls out with a SIM switch if that's unknown

Soundrecorder and sound tests in the settings audio view works very well. But calls doesn't work by me.
