### ISSUE TITLE
Kernel device tree - front camera OmniVision OV8858

### ISSUE THREAD

**Issue by bjadel** [dreemurrs-embedded/Pine64-Arch#259]
- Device: PinePhone Pro
- Kernel Version : 5.16.0-rc3-1-danctnix
- UI: Phosh

```
[alarm@danctnix ~]$ cat /proc/device-tree/i2c\@ff110000/camera\@3c/compatible 
ovti,ov5640
[alarm@danctnix ~]$ cat /proc/device-tree/i2c\@ff110000/camera\@1a/compatible
sony,imx258
```

I think the kernel device tree is not correct because my Pinephone Pro probably has the OmniVision OV8858 front camera installed. See [here](https://pine64.com/product/pinephone-pro-developer-edition-invitation-only/). 

How can I check which camera is actually installed in my case?

**Comment by Danct12** [comment]
There should be support for the front camera in the kernel as well in libcamera. Closing.
