### ISSUE TITLE
Use F2FS for future images

### ISSUE THREAD

**Issue by Danct12** [dreemurrs-embedded/Pine64-Arch#27]

**Comment by Danct12** [comment]
After some research, you actually cannot shrink F2FS partition yet, makes it very uncomfortable for use with P-Boot.

So there's currently no plan for F2FS, yet.

**Comment by Danct12** [comment]
We decided to NOT use F2FS due to stability reasons. This will be reopened in the future.

**Comment by Teteros** [comment]
Why not set `CONFIG_F2FS_FS` in linux-pine64 so we can still use F2FS manually?
Currently you have to use another kernel for this and I couldn't get Arch running with XNUX/P-Boot one for some reason.

**Comment by Danct12** [comment]
F2FS is now used on images from 2020/12/03 and now on.
