### ISSUE TITLE
PPP no fast/rapid charge after latest (5.16.0-1-danctnix/linux-firmware20211216.f882ecb-1) update

### ISSUE THREAD

**Issue by fbmoose48** [dreemurrs-embedded/Pine64-Arch#274]
Device: PinePhone Pro
    Kernel Version : 5.16.0-1-danctnix
    UI: Phosh
    linux-firmware20211216.f882ecb-1

### Expected behavior

charge rapidly

### Actual behavior

very slow charge, reports < 1 Amp @ 5V, estimate over 32 hours to full (16 hrs at 50%)

### Logfiles and additional information
had been charging rapidly only a few days ago, prior to updates to kernel/fw.

**Comment by Danct12** [comment]
Tried unplug and plug back in? This is a known bug with the kernel.

**Comment by fbmoose48** [comment]
resolved, but if its a bug may reoccur until fixed. thanks
