### ISSUE TITLE
No phosh splash screen

### ISSUE THREAD

**Issue by NoahAndrews** [dreemurrs-embedded/Pine64-Arch#276]
Phosh 0.14.0 includes "Launch splash support", but I'm running phosh 0.14.1-1 on Arch Linux ARM, and I'm not seeing any splash screens while apps launch.

**Comment by Danct12** [comment]
Not all application supports launch splash.

GTK apps however should natively support it, this is how Megapixels did it: https://gitlab.com/postmarketOS/megapixels/-/commit/d9866f6029034a0c6cfb4b8b1d8ddab7ec519985
