### ISSUE TITLE
Can't add new google account in phosh Online Accounts setting

### ISSUE THREAD

**Issue by lisael** [dreemurrs-embedded/Pine64-Arch#280]
- Device: PinePhone
- Kernel Version : 5.16.0-1-danctnix
- UI: Phosh

### Steps to reproduce

Go to Settings -> Online Accounts

Choose Google

An embed browser displays accounts.google.com login page. Enter your gmail address and click [Connect]

### Expected behavior

The oauth connection works.

### Actual behavior

We get a page from google stating  "Cannot connect, This browser or application are maybe not secure" (Rough translation, I couldn't get it to display the page in english)

### Logfiles and additional information

It was working 6 month ago, It was still working two days ago on PMOS (distro-hopping recently)

EDIT: I've reported the issue upstream, too: https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/1571

**Comment by Danct12** [comment]
Google is known to do this, so I'm not surprised. It'll get fixed soon eventually.

**Comment by lisael** [comment]
Update: I managed to add one single account, then I had the issue for another account seconds later. It seems to be on Google part, yes. (Both accounts did work 6 month ago on Arch and days ago on PMOS)

I definitely try to debug this with gnome devs.
