### ISSUE TITLE
gnome-calendar-mobile "New Event..." does not open

### ISSUE THREAD

**Issue by mikeshenson** [dreemurrs-embedded/Pine64-Arch#284]
- Device: PinePhone 32G
- Kernel Version : 5.16.1-2-danctnix
- UI: Phosh 
- gnome-calendar-mobile 41.2-1

### Steps to reproduce
Month view >> Click on the "+2" >> Press New Event... >> Nothing happens

### Expected behavior
I expect the new event window to open

### Actual behavior
Nothing happens

![MonthNewEvent](https://user-images.githubusercontent.com/7337270/150623157-cddd2367-e4c7-4ecc-9da4-8fa5ee1051b7.png)

**Comment by mikeshenson** [comment]
I created an upstream issue here
https://gitlab.gnome.org/GNOME/gnome-calendar/-/issues/797

**Comment by Danct12** [comment]
Yes, GNOME Calendar was not adaptive on mobile by default. This is where that Purism repo comes into place, we get the patches from there and use them.

**Comment by mikeshenson** [comment]
On my phone, I uninstalled gnome-calendar-mobile and installed the gnome-calendar from extra. 
I could reproduce this issue with gnome-calendar from extra, this is why I closed the issue here and opened it up with gnome.
![MonthNewEvent3](https://user-images.githubusercontent.com/7337270/153739618-96d8db71-d7ed-4bd4-9495-7ebc3102daac.png)
.

**Comment by mikeshenson** [comment]
So... 
Issue #285 and Issue #286 should be moved to source.puri.sm?
