### ISSUE TITLE
Include arch-install-scripts in install images

### ISSUE THREAD

**Issue by dariox86** [dreemurrs-embedded/Pine64-Arch#291]
- Device: PinePhone 1.2b
- Kernel Version : 5.16.2-2-danctnix
- UI: Phosh

### Steps to reproduce
My PinePhone was stuck at boot after it froze during an update of glib2. When attempting to recover the system using a microSD with a barebone image, I realized arch-chroot was missing.

### Expected behavior
I expected to find arch-chroot in the install image as in Arch Linux for x86-64.

### Actual behavior
Unlike Arch Linux for x86-64, arch-install-scripts was not installed by default.

**Comment by Danct12** [comment]
arch-install-scripts isn't installed by default on x86 either, unless you're booting off the official installation iso or having dependencies that require it.

No reason to include this by default.
