### ISSUE TITLE
Improve documentation by explaining how to add support for eMMC modification

### ISSUE THREAD

**Issue by dariox86** [dreemurrs-embedded/Pine64-Arch#292]
- Device: PinePhone
- Kernel Version : 5.16.2-2-danctnix
- UI: Phosh

### Steps to reproduce
Installing Arch Linux ARM DanctNIX on a PinePhone with a modified eMMC does not work out of the box

### Expected behavior
A note in the wiki explaining what to do to have a modified PinePhone to boot. I can send a pull request.

### Actual behavior
A modified PinePhone does not work out of the box.

**Comment by Danct12** [comment]
I was thinking of packing up vccq.zip and tell people how to apply it, since it's not possible to apply it within the system thus no point to make a package for that.

BTW, the wiki is open, you can make a new page for that.

**Comment by dariox86** [comment]
I can take care of the wiki. What link should I supply to point out the relevant files to add?

**Comment by xnopasaranx** [comment]
I would love to have that information right now... any chance you could add that wiki page @dariox86 ?

**Comment by dariox86** [comment]
At the moment I am at work. Basically [this](https://github.com/dreemurrs-embedded/Pine64-Arch/issues/263#issuecomment-1013928271) is everything you need to do.

**Comment by Danct12** [comment]
https://github.com/dreemurrs-embedded/Pine64-Arch/discussions/656
