### ISSUE TITLE
Pinephone keyboard does not work with UBPorts edition

### ISSUE THREAD

**Issue by caveman250** [dreemurrs-embedded/Pine64-Arch#297]
- Device: PinePhone UBPorts
- Kernel Version : 5.16.3-2-danctnix
- UI: Phosh 0.15

### Steps to reproduce
Connect the pinephone keyboard

### Expected behavior
pressing keyboard keys results in a key press being registered on the device.

### Actual behavior
nothing happens

Keyboard works flawlessly on my pinephone pro, and pinephone beta edition

**Comment by Danct12** [comment]
Works fine on my UBports edition phone, maybe the pogo pins on your phone has bad contacts, try clean them.

What does `sudo dmesg | grep kb151` reports?

**Comment by caveman250** [comment]
yeah its was my pins needing a clean oops! 

thanks :)
