### ISSUE TITLE
Plasma keyboard charging function doesn't really work

### ISSUE THREAD

**Issue by Dan-Sun** [dreemurrs-embedded/Pine64-Arch#299]
- Device: PinePhone
- Kernel Version : 5.16.4-1-danctnix
- UI: Plasma

### Steps to reproduce
Latest version of Plasma seems to have some issues with the new keyboard case.

### Expected behavior
I moved to fde plasma yesterday. Coming from manjaro beta10. The combination of phone and keyboard worked really good on manjaro. Just one click on the keyboard's power button will easily enable or disable the keyboard's charging function. Charging both devices through the keyboard usb port works.

### Actual behavior
Can't disable charging function.
Charging through keyboard usb port doesn't work.
Both devices are fully charged over night and it shows only 50%max.

### Logfiles and additional information
Any suggestions here?

**Comment by Danct12** [comment]
Superseded by #304
