### ISSUE TITLE
Keyboard not reporting charge capacity under userspace (always reads 0%)

### ISSUE THREAD

**Issue by fbmoose48** [dreemurrs-embedded/Pine64-Arch#304]
- Device: PinePhone Pro
- Kernel Version : 5.16.4-1-danctnix
- UI: Phosh

### Steps to reproduce
Plug charger in keyboard, "main" battery charges, but both "extra" and "kb151" show `0%` in gnome-settings power submenu

### Expected behavior
both "main" and "kb151" charge to 100%

### Actual behavior
only "main" charges to "100%", "kb151" always reads as "0%"

this may be a reporting problem with Arch or Phosh as the "main" battery charge seems to continue to rise even when usb unplugged, leading me to believe its charging off the reportedly 0% kb151 battery.

**Comment by jwcrawley** [comment]
I just got my pinephone pro explorer edition, with a pinephone keyboard/battery. Same issue. 

I also noticed that according to this link https://xnux.eu/pinephone-keyboard/faq.html#charging , that the binary/script "ppkb-i2c-charger-ctl" is not on this image. 

I'm going to try to install this package and try again.

**Comment by fbmoose48** [comment]
`ppkb-i2c-charger-ctl` installs from AUR with `pinephone-keyboard`. I've had it installed for 2 days through multiple reboots, no change in battery status

**Comment by Dan-Sun** [comment]
I have plasma running on emmc and phosh on sd card. I guess the problem occurs on both. I created an issue for plasma https://github.com/dreemurrs-embedded/Pine64-Arch/issues/299 a few days ago that shows the same behavior.

**Comment by Danct12** [comment]
IIRC battery value readings doesn't seem to be a feature yet with the keyboard driver. The last time I tried this, the same 0% happened there too.

**Comment by Danct12** [comment]
@Dan-Sun I ran into the kernel module error from the log. This is documented on [megi's keyboard FAQ](https://xnux.eu/pinephone-keyboard/faq.html).

> ppkb-i2c-charger-ctl info prints some 0xff error:
>>Sadly, charger chip sometimes goes to sleep and doesn't respond to I2C communication in this state. Wake it up by pressing the keyboard power button, or by inserting a power supply to the keyboard's Type-C port. This is a HW limitation.

**Comment by Danct12** [comment]
You need to put `kb151.disable_input` to the kernel command line before the input daemon could work.

**Comment by Dan-Sun** [comment]
Thanks!

It works great. Even keymap is right now.

> How can I read the battery capacity?
    Keyboard's power supplies are represented by ip5xxx-charger and ip5xxx-boost in /sys/class/power_supply 
    You can read the battery voltage and charging/discharging current. Capacity is not readable from the charger chip directly, it needs to be guessed/calculated from the open circuit voltage and the battery discharge curve. I have measured the curves of my keyboard. I have yet to process the data. 

That's still an issue.

**Comment by Dan-Sun** [comment]
`kb151.disable_input` doesn't work after the latest linux-megi update.

Are you aware of any particular changes?

**Comment by Danct12** [comment]
Yes, it's changed to `pinephone-keyboard.disable_input`.

**Comment by Danct12** [comment]
I'll also be closing this as keyboard battery capacity reporting has been implemented in latest kernel releases.
