### ISSUE TITLE
Screen black after unlock

### ISSUE THREAD

**Issue by fuchsmich** [dreemurrs-embedded/Pine64-Arch#31]
I just flashed the latest image 20200814 to the emmc.
The unlock screen shows up. After entering the code 123456 , it shows the language selection dialog.
But after selecting a language or pushing next, the screen fades to black.

How can I solve this?

**Comment by Danct12** [comment]
Duplicate issue of #22

**Comment by fuchsmich** [comment]
Thx and sorry for the noise.
