### ISSUE TITLE
Can not receive Sms

### ISSUE THREAD

**Issue by Csanderson03** [dreemurrs-embedded/Pine64-Arch#316]
I can send text but can not receive text.

- Device: (PinePhone or PineTab?)
- Kernel Version : $(uname -r)
- UI:

**Comment by Danct12** [comment]
You haven't filled out the form. Please spend sometime on providing the data needed for the report.

**Comment by fbmoose48** [comment]
https://forum.pine64.org/showthread.php?tid=9687&pid=64706#pid64706
