### ISSUE TITLE
Keyboard - Keep shift, fn ... hold on double click

### ISSUE THREAD

**Issue by Dan-Sun** [dreemurrs-embedded/Pine64-Arch#318]
- Device: Keyboard

It's not an issue, I just need a direction/hint where I can play around with the keymap?! I'm looking for to add for example - hit shift twice to keep it pushed, same for fn and others. It's just a bit annoying to move your right hand to the left side of the keyboard.

**Comment by Danct12** [comment]
The keymap is in the driver itself, and if you're using the userspace daemon then it's in the daemon too. You need to recompile the daemon if you want to change the keymap.

We have a forum on Pine64's forum if you need to discuss about non-bugs stuffs. https://forum.pine64.org/forumdisplay.php?fid=159
