### ISSUE TITLE
[docs] Explain testing repo source

### ISSUE THREAD

**Issue by 3nprob** [dreemurrs-embedded/Pine64-Arch#331]
It would be helpful to understand where packages in hosted repos are built from. Crucial for those who want to build their own parallel mirrors.

I assume that the main repo `https://p64.arikawa-hi.me/danctnix/aarch64/` has packages from the latest tagged release (or is it nightlies from `master`)?

How about `https://p64.arikawa-hi.me/danctnix-testing/aarch64/`?

**Comment by Danct12** [comment]
danctnix-testing are fresh packages.

Basically any new packages from master will have to go in testing first. If deemed stable it'll go in the main repo.
