### ISSUE TITLE
invalid or corrupted package (PGP signature)

### ISSUE THREAD

**Issue by fbmoose48** [dreemurrs-embedded/Pine64-Arch#339]
------------------------------------------------------------------------------
--------------------------------------------------------------------------------

- Device: PinePhone 
- Kernel Version : 5.16.10-1-danctnix
- UI: Phosh

### Steps to reproduce
sudo pacman -Syu

### Expected behavior
updates

### Actual behavior
returns 
`error:signature from "DanctNIX Build System <builder@main-key.danctnix.org>" is unknown trust`
`error: failed to commit transaction (invalid or corrupted package (PGP signature))`

Is there a user-side fox for this, or does a key need to be updated server-side?

**Comment by Danct12** [comment]
I never had this issue, can you try to run `sudo pacman-key --populate danctnix`?

**Comment by fbmoose48** [comment]
that fixed it, thanks!
