### ISSUE TITLE
Add kbdaemon package and change charging power in initramfs

### ISSUE THREAD

**Issue by edgar-vincent** [dreemurrs-embedded/Pine64-Arch#347]
- Device: Pinephone (should apply to PPP too)
- Kernel Version : 5.16.13-1-danctnix
- UI: Phosh

Would https://gitlab.com/undef1/kbd be a welcome addition? It is a daemon which disables `squeekboard` and sets `input_current_limit` to a higher value when the keyboard is attached. I made a PKGBUILD for it there: https://git.sr.ht/~e-v/aur-kbd-git.

Moreover, for FDE/OSK-SDL users (or indeed any PPKB users), it would be useful to set `input_current_limit` to a higher value with a `mkinitcpio` hook when the keyboard is attached so the phone charges faster before boot. Currently, if the battery is dead and the phone is off, it takes a very long time to charge the phone up enough so that it can boot, and one is stuck in a sort of boot loop to `osk-sdl`.

**Comment by Danct12** [comment]
I think this is no longer necessary, as megi said in this blog post: https://xnux.eu/log/#065 . This should now be handled by the kernel, and starts charging the phone battery first before charging the keyboard battery.
