### ISSUE TITLE
unable to send/receive SMS

### ISSUE THREAD

**Issue by fbmoose48** [dreemurrs-embedded/Pine64-Arch#352]
- Device: PinePhone Braveheart
- Kernel Version : 5.16.14-1-danctnix
- UI:  phosh

### Steps to reproduce
can't send/receive SMS, but can place/receive calls

### Expected behavior
SMS work

### Actual behavior
SMS not working

### Logfiles and additional information
I had faced SMS issues related to modem cache in the past, but had been able to manage by by connecting to the modem tty through minicom and clearing cache with "AT+CMGD=0,4". Now that doesn't seem to work anymore.

**Comment by Danct12** [comment]
IIRC, this might had to do with 3G/4G thing, try switch to 3G and see if you can receive SMS.

**Comment by Danct12** [comment]
Closing as the reporter hasn't responded to the issue for a year now.
