### ISSUE TITLE
Waydroid only works with hardward acceleration disabled

### ISSUE THREAD

**Issue by DSchroer** [dreemurrs-embedded/Pine64-Arch#353]
- Device: Pinephone Pro
- Kernel Version : 5.16.14-1-danctnix
- UI: Phosh

### Steps to reproduce
1. install waydroid: `sudo pacman -S waydroid`
2. setup images: `sudo waydroid init`
3. start service `sudo systemctl enable waydroid && sudo systemctl start waydroid`
4. launch UI `waydroid show-full-ui`

### Expected behavior
Waydroid UI Opens

### Actual behavior
The UI tries to open but the screen becomes glitchy and unresponsive.

Had to disable hardware acceleration first: `( sudo echo "ro.hardware.gralloc=default" ; sudo echo "ro.hardware.egl=swiftshader" ) >>/var/lib/waydroid/waydroid_base.prop`

Now the UI loads but is slow.

**Comment by e-dorigatti** [comment]
It's not an arch-specific issue as I have the same issue with PostmarketOS+Phosh/PlasmaMobile on the Pinephone Pro, while everything is fine on the non-pro (arch+phosh).

**Comment by DSchroer** [comment]
If that's the case which project should this be referred to?

**Comment by Arsen6331** [comment]
I've already opened an issue for this: waydroid/waydroid#291

**Comment by rothn** [comment]
Building from latest repo sources seems to solve the problem: [guide](https://docs.google.com/document/d/1Sly_VH3w6wFIdE72WXijQegoHZh8IxEnJ9m0hH7GodU/edit#)
