### ISSUE TITLE
Latest u-boot does not wake from suspend

### ISSUE THREAD

**Issue by fbmoose48** [dreemurrs-embedded/Pine64-Arch#354]
- Device: PinePhone Pro
- Kernel Version : 5.16.14-1-danctnix
- UI:  phosh

### Steps to reproduce
update u-boot, let phone suspend

### Expected behavior
wakes from suspend

### Actual behavior
does not wake, appears "off" and needs to be manually rebooted 

### Logfiles and additional information
I had been on the u-boot included in the 20220212 release and wake had improved. upgraded u-boot and wake stopped working. flashed back to the 20220212 u-boot and wake works again.

**Comment by Danct12** [comment]
I can confirm this issue as well, I've reverted that patch for now. And it looks like Caleb came up with a better fix than U-Boot hack.
