### ISSUE TITLE
Unable to add a printer in Arch Linux phosh

### ISSUE THREAD

**Issue by jsarkari** [dreemurrs-embedded/Pine64-Arch#363]
- Device: (PinePhone or PineTab?) PinePhone Pro
- Kernel Version : $(uname -r) 5.17.0-2-danctnix
- UI: phosh

### Steps to reproduce

Open settings, printers
Add a printer

### Expected behavior

Ability to add a printer on wifi etc

### Actual behavior

Sorry! The system printing service doesn't seem to be available.

**Comment by Danct12** [comment]
The error can be fixed by installing `cups` and enable the service, I'll enable this for the next image.

**Comment by jsarkari** [comment]
I installed cups:

sudo pacman -S cups

So I can now add a printer via wifi or usb directly however I then got a system notification:

Additional Printer Drivers Required
An application is reqesting additional printer drivers.

Find in Software

This is an EPSON ET-2750 printer.

**Comment by Danct12** [comment]
Hi, it looks like your printer requires a driver (see [Arch Wiki](https://wiki.archlinux.org/title/CUPS/Printer-specific_problems#Epson)).

Please try to build and install the driver for your specific printer (for your printer, it should be [epson-inkjet-printer-escpr](https://aur.archlinux.org/packages/epson-inkjet-printer-escpr) from AUR), this might make the printer working.

**Comment by jsarkari** [comment]
Yes I am doing some research to resolve the issues. I have now managed to add the ppd file via localhost:631 so getting closer.

**Comment by Danct12** [comment]
This is now included in Phosh and Plasma images. I'll be closing this as this seems to be a issue with your printer model under Linux.
