### ISSUE TITLE
alsa-card-profiles 1:0.3.50-1 breaks call audio (PPP)

### ISSUE THREAD

**Issue by fbmoose48** [dreemurrs-embedded/Pine64-Arch#378]
- Device: PinePhone Pro
- Kernel Version : linux-megi (5.17.0-2)
- UI:  phosh

### Steps to reproduce
Place call, no audio/mic

### Expected behavior
audio profile for calls works

### Actual behavior
silence

### Logfiles and additional information
downgrading package alsa-card-profiles (1:0.3.50-1 => 1:0.3.49-1) fixed issue

**Comment by Danct12** [comment]
I'll investigate this, for now, I've added 0.3.49 to the repo so it won't auto update to it.

**Comment by greg-hellings** [comment]
Downgrading did not give audio in calls. I did not have it before the upgrade either. Including with the most recent release clean installed. Audio works fine outside of call configuration.

**Comment by Danct12** [comment]
All of this might be related to this: https://archlinux.org/news/undone-replacement-of-pipewire-media-session-with-wireplumber/

I'm currently running the latest image and updated everything, still works.
