### ISSUE TITLE
Audio becoming too fast after suspend and resume

### ISSUE THREAD

**Issue by jsarkari** [dreemurrs-embedded/Pine64-Arch#381]
- Device: (PinePhone or PineTab?) Pinephone Pro
- Kernel Version : $(uname -r) 5.17.4-1-danctnix
- UI: phosh

### Steps to reproduce

Open firefox
Go to bbc.com/news
Open an article where there is an embedded video
Start playing the video

### Expected behavior

Plays at normal speed so you can comprehend what is being said

### Actual behavior

It plays at 3-4 times the speed so they sound like mice!

Furthermore there is no option in video playback to change any settings like speed, adding subtitles etc

**Comment by jsarkari** [comment]
Is there a way to force suspend rather than waiting the minimum 5 minutes?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Danct12** [comment]
Yes, run `systemctl suspend` in the terminal.

**Comment by jsarkari** [comment]
Yes found that and it worked, odily it was also doing it in chromium browser also.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Danct12** [comment]
That is because it's not a Chromium or any program issue, but rather a issue in the audio driver itself.

**Comment by GertVanKruiningen** [comment]
Suspending using "systemctl suspend" or waiting for the PPP to suspend, does fix the audio issue, but doesn't always work.
Suspending switches between "fast" and "normal" speed, but no idea yet why its not consistent.

**Comment by jsarkari** [comment]
I could always record the songs and sell as remixes!

**Comment by caveman250** [comment]
Is there an issue or thread that can be followed for the driver bug? would love to find out more, especially as to why suspending only fixes the issue sometimes.

**Comment by dukla2000** [comment]
I still have this issue with 5.19.3-1
Re-creatable by installing archlinux-pinephone-pro-phosh-20220729.img
edit /etc/pacman.conf and enable testing repo
pacman -Syu

Reboot, allow to suspend after 5 mins. Push power button - PPP comes back to life. Any sound (e.g. ping when plugging in power) actually results in about 10 second of "short wave radio" (this has changed from Mickey Mouse at earlier kernel revs.)

I have never been able to get multiple suspend/resume cycles to give me any different result.

I can't see anything peculiar (to my eye) in the journal worth reporting

**Comment by Danct12** [comment]
I'll be closing this issue for now since a lot of people has this problem fixed on their end with the latest kernel.
