### ISSUE TITLE
Porting to OnePlus 6T

### ISSUE THREAD

**Issue by snnbyyds** [dreemurrs-embedded/Pine64-Arch#389]
Hello, I managed to run Archlinuxarm on my OnePlus6T and succeeded in using GNOME. Then I tried to use plasma mobile on Archlinux. I added the source (https://p64.arikawa-hi.me/) and installed most of the package same as danctnix's github release. However my phone just entered tty. I am wondering how to get plasma mobile start at boot.

**Comment by charlesDelaware** [comment]
Did you  give this a  go and reboot?

` sudo systemctl disable gdm && sudo systemctl enable simplelogin`

**Comment by Danct12** [comment]
Unfortunately we do not support anything other than the PinePhone/PinePhone Pro and PineTab 2. Closing.
