### ISSUE TITLE
archlinux-pinephone-phosh-20220502.img.xz  cannot find WiFi in PinePhone BETA

### ISSUE THREAD

**Issue by wcdeich4** [dreemurrs-embedded/Pine64-Arch#390]
archlinux-pinephone-phosh-20220502.img.xz  cannot find WiFi in PinePhone BETA

**Comment by wcdeich4** [comment]
I bought the beta edition that does not include the dock :(  I guess I could buy a dock.  Is there any way to connect to lan with a dock?

**Comment by hannescam** [comment]
no without a dock your have no options to connect to the internet without wifi ecxept you have some sort of usb c to usb a female adaptor and a usb ethernet dongle or a usb c ethernet dongle it is also possible with mobile data

**Comment by Danct12** [comment]
I was unable to reproduce this problem, your battery might be too discharged. What happens if you unplug the USB cable?

**Comment by wcdeich4** [comment]
Hi, I had a few minutes to test it.  I downloaded a fresh copy of archlinux-pinephone-phosh-20220502.img.xz, put it on a new SD card & tested it w/out the PinePhone BETA without the power cord connected & WiFi worked.  Not sure if I had a bad download, bad SD card or not connecting the usb cable made the difference, but it is working now.  Sorry to bother you.
