### ISSUE TITLE
locale-gen occurs everytime glibc updates

### ISSUE THREAD

**Issue by Danct12** [dreemurrs-embedded/Pine64-Arch#41]
This takes a very VERY long time. So fix it.

**Comment by ScardracS** [comment]
Personally I modify /etc/locale.gen in order to maintain only languages I really need (so en.US and it.IT).
Everyone should use that or add a script that permit to select only languages we are interested on (like localepurge)

**Comment by Danct12** [comment]
Hmm, maybe the idea here is to generate glibc locale during buildtime and then ship it to users?

**Comment by ScardracS** [comment]
@Danct12 probably better, but if an update occurs the problem still be here

**Comment by Danct12** [comment]
We can disable that ability, there's no point to run locale-gen again once the locales are all installed.

**Comment by Danct12** [comment]
So that is now fixed, I'll push out newer images that get around the problem.

But for older images, you need to install `glibc-locales` from the repository and clean `/etc/locale.gen`.
