### ISSUE TITLE
Regression: unable to launch Waydroid after updating from linux-megi-5.17.6-1 to linux-megi-5.18.0-2

### ISSUE THREAD

**Issue by dariox86** [dreemurrs-embedded/Pine64-Arch#412]
- Device: PinePhone
- Kernel Version : 5.18.0-2-danctnix
- UI: Phosh

### Steps to reproduce
Upgrade from linux-megi-5.17.6-1 to linux-megi-5.18.0-2, reboot the device and launch Waydroid.

### Expected behavior
After a while Waydroid should show up.

### Actual behavior
Waydroid does not show up.

**Comment by Danct12** [comment]
Please run `waydroid upgrade -o` to update the config for 5.18.

**Comment by dariox86** [comment]
Stupid me, this is in the Arch Wiki. It works. Thank you.
