### ISSUE TITLE
Some PinePhone Pro display doesn't work after the latest update

### ISSUE THREAD

**Issue by Danct12** [dreemurrs-embedded/Pine64-Arch#418]
- Device: PinePhone Pro
- Kernel Version : 5.18.3-1-danctnix
- UI: any

### Steps to reproduce
Get the latest image (05/02/2022 as of the current time of this issue), flash it and update. Reboot.

### Expected behavior
Should boot like normal

### Actual behavior
On some devices, this shows a black screen

### Logfiles and additional information
No logs, I'm not sure what happened as I do not run into this issue, as well as some people in chat, but it does happen to some people.

It might be possible to get logs (dmesg, journalctl) if you have SSH and the system is still booting (without the display).

**Comment by Stev18** [comment]
This happens for me consistently after running updates, but I can still go into shared-storage mode. If you can tell me where to find the logs you need, I can post them here.

**Comment by BillFleming** [comment]
This isn't happening on my PPP. Have an older Danctnix Posh install from around Feb or March. Updated to 5.18.3-1 kernel last week and no issues after reboot. Did an update just now and rebooted and still no issues. Currently this install is still on an SD card and I didn't purge the old uboot stuff on the sd card yet (or convert to gpt). But towboot is installed to SPI.

**Comment by sado1** [comment]
I have SSH access. I see the following error in journalctl -b:
`cze 22 09:41:42 danctnix phoc[3230]: [backend/backend.c:217] Found 0 GPUs, cannot create backend
cze 22 09:41:42 danctnix phoc[3230]: [backend/backend.c:311] failed to add backend 'drm'
cze 22 09:41:42 danctnix phoc[3230]: Failed to create server: Could not create backend
`

**Comment by sado1** [comment]
Downgrading to kernel linux-megi-5.17.6-1 seems to workaround the issue.

**Comment by prurigro** [comment]
So my older emmc install isn't getting the issue when I upgraded it, but a newer one flashed to an SD card is getting the issue on the same PPP... I'm not sure if the issue is the sd card or something different about it being a fresh install?

**Comment by Danct12** [comment]
Can you post the dmesg? The error you posted isn't informative enough for tracking down the problem. @sado1

**Comment by Dan-Sun** [comment]
It was the mesa package for me. I had to downgrade, reboot and update again. It seems to work on this end so far.

**Comment by CCF100** [comment]
> It was the mesa package for me. I had to downgrade, reboot and update again. It seems to work on this end so far.

@Dan-Sun What mesa package version works for you?

**Comment by Dan-Sun** [comment]
@CCF100 
The mesa package helped me on ppp without FDE (SD card), but I just installed the latest FDE (phosh) on emmc and nothing helped except the suggested kernel downgrade (linux-megi (5.18.4-1 => 5.17.6-1)).
Maybe again a FDE problem with `osk-sdl`?!

Does everyone here use FDE?

**Comment by bobjrsenior** [comment]
I'm not using FDE

**Comment by slackerbob** [comment]
I am on FDE and downgrading the kernel to 5.17.6-1 worked for me, too.

**Comment by CCF100** [comment]
> @CCF100 The mesa package helped me on ppp without FDE (SD card), but I just installed the latest FDE (phosh) on emmc and nothing helped except the suggested kernel downgrade (linux-megi (5.18.4-1 => 5.17.6-1)). Maybe again a FDE problem with `osk-sdl`?!
> 
> Does everyone here use FDE?

I use FDE

**Comment by Dan-Sun** [comment]
It probably has nothing to do with FDE or non-FDE.

My FDE is the latest release I'm using that has the problem. My non-FDE was the one in January or February that does not have the problem. 
So maybe it''s related to the last release. Would be great if someone with this problem and without FDE could provide more logs. I tried to get access with FDE but it's quite complicated ;)

**Comment by megous** [comment]
On my 5.18+ kernel branch, cameras must probe successfully for the display to work. It's due to DRM sharing DSI-PHY between display and camera/V4L2 uses. Maybe it's caused by that. dmesg would confirm it.

**Comment by Danct12** [comment]
wait, so we have to make the camera modules built in or what?

**Comment by ollieparanoid** [comment]
Possibly related to serial cable being plugged (not megi's tree though): https://gitlab.com/postmarketOS/pmaports/-/issues/1603

**Comment by sado1** [comment]
> On my 5.18+ kernel branch, cameras must probe successfully for the display to work. It's due to DRM sharing DSI-PHY between display and camera/V4L2 uses. Maybe it's caused by that. dmesg would confirm it.

And the reason only some people had this problem, is likely that they disabled the camera switches below the battery cover - just like I did. I've updated my kernel again, and it boots with screen working, as long as the switches are turned on.

**Comment by Dan-Sun** [comment]
Hm, I have the front camera disabled and changed it back but it doesn't work for me.

**Comment by slackerbob** [comment]
The switches don't seem to have any effect on the issue for me.

**Comment by CCF100** [comment]
> The switches don't seem to have any effect on the issue for me.

Neither do they have any effect for me...

**Comment by sado1** [comment]
Could there be any other reason that one of your cameras is disabled?
Did you disable any other switch? All of them are enabled in my PPP.

**Comment by slackerbob** [comment]
All of them are enabled on my ppp with fde. Though, I've never seen the ppp camera actually work, so who knows if it's broken somewhere else. Megapixels just crashes on load. I had assumed the drivers weren't live yet.

**Comment by Dan-Sun** [comment]
I use https://github.com/Biktorgj/pinephone_modem_sdk maybe its related to that?

**Comment by sado1** [comment]
> I use https://github.com/Biktorgj/pinephone_modem_sdk maybe its related to that?

I use it as well, and with camera switches on, it works fine for me.

**Comment by tricepsbrachii** [comment]
Don't have much to add other than I've been having this problem too and pinning at `linux-megi-5.17.6` is a workaround for now. I still need to investigate this, but it's very similar to an issue I had on PBP, where the screen would blank after loading the initramfs , preventing seeing the password entered in plymouth. It was still possible to enter the password, and after some bit of time the display would initialize (I guess). Of course, if FDE was off, everything would work fine because the screen would eventually activate during the course of the boot process.

Here is the related issue for PBP in manjaro-arm: https://gitlab.manjaro.org/manjaro-arm/applications/manjaro-arm-installer/-/issues/44

I tried adding `panel_edp` to `MODULES~ in `/etc/mkinitcpio.conf`, but that didn't help PPP boot the latest kernel. But I think it's something in this direction, since both devices are rk3399. I'll keep investigating.

**Comment by Nuss9940** [comment]
After enabling the camera switches and updating to the latest kernel, the display works fine for me

**Comment by sado1** [comment]
> @sado1 do you use FDE?
I don't.

**Comment by wellDressedCodePenguin** [comment]
I can confirm Nuss9940's findings, I've written more on another issue on the Manjaro-arm Distrobution's gitlab: https://gitlab.manjaro.org/manjaro-arm/issues/pinephone/phosh/-/issues/258

I hope this helps.

**Comment by megous** [comment]
It's simple, the rear camera driver has to probe the camera successfully, otherwise display will not work.

**Comment by megous** [comment]
So the imx258 cam driver has to load from initramfs or if builtin, you need U-Boot which will configure I/O voltages on camera I2C bus properly. Tow-boot is not doing it properly:

https://github.com/Tow-Boot/Tow-Boot/blob/released/boards/pine64-pinephonePro/0001-pine64-pinephonepro-device-enablement.patch#L2640

It's not configuring audio_gpio3d4a_ms to 1.8V as it must.

https://megous.com/dl/tmp/44e506bd7622dd30.png

**Comment by megous** [comment]
https://github.com/megous/linux/commit/51cd30c9cb96b90595de1772a0592f77a2dbf072

**Comment by tricepsbrachii** [comment]
Looks like PPP is now booting with a functional display with `osk-sdl` with the latest tag of your kernel branch, thank you @megous !

**Comment by Danct12** [comment]
Can you please post your dmesg? This information isn't that useful for tracking down the problem.

**Comment by Danct12** [comment]
This seemed to have been fixed a long while ago, let's close this.
