### ISSUE TITLE
How to update uboot on pinephone

### ISSUE THREAD

**Issue by mogwa1** [dreemurrs-embedded/Pine64-Arch#42]
I've updated uboot-pinephone through pacman.  However, the instructions to install the bootloader are not correct anymore.
It seems that the uboot-pinephone package now contains three versions of the u-boot-sunxi-with-spl-pinephone-xxx.bin file, with xxx being 492, 552 or 624.
Shouldn't the package contain just one version?

**Comment by 0p3t** [comment]
sudo dd if=/boot/u-boot-sunxi-with-spl-pinephone-624.bin of=/dev/mmcblk2 bs=8k seek=1 worked just fine for me. Guess the instructions on the updater need, well, updating.

**Comment by mogwa1** [comment]
Ok, thanks.  I've just flashed this one, and it's fine now.
The main problem was that I didn't know which of the three should be installed, or what the difference is between the three versions.

**Comment by Danct12** [comment]
These multiple versions are for devices that works better with lower DRAM clock. Usually if you have no issue then you'll be using 624. (see #9)

I'll add this to the wiki soon.
