### ISSUE TITLE
mesa-git | pacman -Syu: could not satisfy dependencies required by mesa-git

### ISSUE THREAD

**Issue by langfingaz** [dreemurrs-embedded/Pine64-Arch#424]
Device: PinePhone (Phosh)

When running `pacman -Syu` I get the following error:

```
installing llvm-libs (14.0.6-1) breaks dependency 'llvm-libs<14' required by mesa-git
```

After reading the pinned comment from [mesa-git](https://aur.archlinux.org/packages/mesa-git#comment-741159) on the AUR, I think that a rebuild of mesa-git is required. mesa-git is part of the `danctnix` repository.

I hope this is the correct place to report this kind of problem and many thanks for taking care of this great project.

**Comment by Danct12** [comment]
I'm closing this as it's fixed in a rebuild.
