### ISSUE TITLE
Haptic Feedback Duration

### ISSUE THREAD

**Issue by zhaofengli** [dreemurrs-embedded/Pine64-Arch#44]
The [default vibration duration](https://source.puri.sm/Librem5/feedbackd/-/blob/9e2c13a1fe228970d933ce05cf56be0ae98a6ae1/data/default.json#L75-79) set for `button-pressed` in feedbackd (15) is not enough for me to feel anything. After some testing, it appears that the minimum duration for the vibration to be perceptible is around 70 (extremely weak, at least for me), and 100 seems to be a sweet spot for short haptic feedback (tested with virtual keyboard). Tweaking the magnitude doesn't seem to have any noticeable effect on such short vibrations.

Should we create a custom feedbackd theme file for PinePhone?

- Device: postmarketOS CE (board 1.2a)
- Version: feedbackd git20200714, squeekboard 1.9.3-0, both from your repo

**Comment by Danct12** [comment]
Implemented in the latest update.
