### ISSUE TITLE
How to change username

### ISSUE THREAD

**Issue by cristiioan** [dreemurrs-embedded/Pine64-Arch#443]
Hello,
Because of some random issue, I need to have the same username as on my desktop on my phone. Is it possible to change it by just deleting the old user and making a new one, or is there something special?

**Comment by phalio** [comment]
You can try this: [https://phal.io/tech/sxmo#rename-user](https://phal.io/tech/sxmo#rename-user) (should work for any UI)

**Comment by Supervisor360** [comment]
go to settings an go to user (it should be near the bottom. press unloc an put your passwrd and then change the name in the name secton. Done! you can also cchange the password too!
