### ISSUE TITLE
Wrong default terminal

### ISSUE THREAD

**Issue by doublez13** [dreemurrs-embedded/Pine64-Arch#45]
I'm a brand new user of Pine64-Arch, so forgive me if this is known or incorrect.

It looks like the default terminal value is set to gnome-terminal, which is not installed by default.
```
[root@p64 ~]# gsettings get org.gnome.desktop.default-applications.terminal exec
'gnome-terminal'
```
Installing a program that launches through the terminal (htop for example), creates an icon on the app screen, but won't lunch due to gnome-terminal not being installed. Installing gnome-terminal fixes the issue, but I would assume changing the exec value to the 'kgx' terminal would be the cleaner solution.

**Comment by doublez13** [comment]
After exploring this further, it looks like Gnome does not respect that dconf key. It simply works it's way down a hard coded list of terminal emulators. Lame. 

https://gitlab.gnome.org/GNOME/glib/blob/master/gio/gdesktopappinfo.c#L2515

**Comment by Danct12** [comment]
Superseded by #182
