### ISSUE TITLE
Enhancement - Request for phosh-plugins in repo

### ISSUE THREAD

**Issue by dukla2000** [dreemurrs-embedded/Pine64-Arch#457]
- Device: PinePhone Pro (but in fact all)
- Kernel Version : 5.19.3-1-danctnix
- UI: Phosh

### Expected behaviour

It seems to support the new lockscreen widgets in phosh 0.21 we need a new module, phosh-plugins, as well. Please can it be added to the repo so we can install?

Ref thread on Pine64 forum [here:](https://forum.pine64.org/showthread.php?tid=17281)
Phosh merge request (I think) [here:](https://gitlab.gnome.org/guidog/phosh-mobile-settings/-/merge_requests/16/diffs)

**Comment by Danct12** [comment]
You can install phosh-mobile-settings and phosh 0.21.0 from testing repo. Be warned that from my testing, the lockscreen widgets are still very buggy and prone to crashing.
