### ISSUE TITLE
Feedbackd missing sound warning spamming journal

### ISSUE THREAD

**Issue by doublez13** [dreemurrs-embedded/Pine64-Arch#46]
The feedbackd config file `/usr/share/feedbackd/themes/default.json` references nonexistent sound files.
In particular, the button-pressed action references a button-pressed file that doesn't exist. This creates a warning in the system journal on every press of the keyboard.
```
Sep 05 15:02:15 p64 feedbackd[3767]: Failed to play sound: File or data not found
Sep 05 15:02:15 p64 feedbackd[3767]: Failed to play sound: File or data not found
Sep 05 15:02:15 p64 feedbackd[3767]: Failed to play sound: File or data not found
Sep 05 15:02:16 p64 feedbackd[3767]: Failed to play sound: File or data not found
Sep 05 15:02:19 p64 feedbackd[3767]: Failed to play sound: File or data not found
Sep 05 15:02:19 p64 feedbackd[3767]: Failed to play sound: File or data not found
```
As mentioned in Bug #44, a custom feedbackd theme file for the PinePhone could be helpful.

**Comment by ahoneybun** [comment]
It looks like this file was created in bug #44 so I think we can close this:

https://github.com/dreemurrs-embedded/Pine64-Arch/issues/44#issuecomment-694099306
