### ISSUE TITLE
the kernel needs additional modules for mobile hotspot to work

### ISSUE THREAD

**Issue by marek-lach** [dreemurrs-embedded/Pine64-Arch#465]
For the  PinePhone mobile hotspot functionality to work properly, the following kernel modules need to be enabled (observed from Mobian):

nf_nat_irc, nf_nat_sip, nf_nat_tftp, nf_nat_pptp, nf_nat_h323

**Comment by langfingaz** [comment]
Hi @marek-lach, on my PinePhone (with Phosh) those kernel modules are loaded and the hotspot functionally is working fine. After I enalbed WiFi I can click on the three dots (in the WiFi settings) and set up a hotspot.

Were those modules disabled in your setup? Did you get it working? And which user interface are you using?
