### ISSUE TITLE
Add ZSTD compression algorithm for zram

### ISSUE THREAD

**Issue by pinoverclock** [dreemurrs-embedded/Pine64-Arch#485]
- Device: PinePhone
- Kernel Version : 6.0.2-1-danctnix
- UI: Phosh

Could you please add CONFIG_CRYPTO_ZSTD module into the kernel so we can use ZSTD compression algorithm with zram?
CONFIG_CRYPTO_ZSTD=y

```
alarm@pp64 ~ $ cat /sys/block/zram0/comp_algorithm
lzo lzo-rle [lz4]
alarm@pp64 ~ $ zcat /proc/config.gz |grep CONFIG_CRYPTO_ZSTD
# CONFIG_CRYPTO_ZSTD is not set
```

Thank you very much guys

**Comment by Danct12** [comment]
Done in 8a8808dbd3a6b67fd1d044825e8951a6ae699b26
