### ISSUE TITLE
Backlight on Keyboard not turned off on standby

### ISSUE THREAD

**Issue by rakor** [dreemurrs-embedded/Pine64-Arch#49]
When the keyboard is attached to the pinetab and the tab is send to standby the backlight of the keyboard stays on

**Comment by Danct12** [comment]
I believe the keyboard don't know how to handle deep suspend, so the backlight is powered no matter if a keyboard is inserted or not.

Another way to get around the issue is to disable the dock USB port before suspending.

**Comment by rakor** [comment]
This could prevent any unecessary powerloss over usb.

**Comment by tomoqv** [comment]
I second this. It would be nice to have the ability to set backlight to off by default.

**Comment by Danct12** [comment]
PineTab 1 is no longer supported. Since this is a hardware issue, there's no way to turn off the backlight on the keyboard.
