### ISSUE TITLE
Adding apps to the new home screen disappear after a reboot

### ISSUE THREAD

**Issue by jsarkari** [dreemurrs-embedded/Pine64-Arch#492]
- Device: (PinePhone or PineTab?) PinePhone Pro
- Kernel Version : $(uname -r) 6.0.2-3-dantix
- UI: KDE Plasma 5.26.2

### Steps to reproduce

Adding apps to the new homescreen as favourites. Then after a reboot they have disappeared.

### Expected behavior

After a restart or reboot the favourite apps should still apear on the new homescreen.

### Actual behavior

The favourites apps disappeared on restart.

**Comment by grinceur** [comment]
yep need to add back the `X-Purism-FormFactor` line in the `.desktop` files

**Comment by grinceur** [comment]
> Is it possible to add that myself as a workaround until it is added. If so where is this file? Thanks
> […](#)
> On 4 Nov 2022 at 14:47, grinceur ***@***.***> wrote: yep need to add back the X-Purism-FormFactor line in the .desktop files — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

hi i was mistaken, this will not solve your issue sorry i misread your report…
