### ISSUE TITLE
Mkimage not working after latest update.

### ISSUE THREAD

**Issue by Laar3** [dreemurrs-embedded/Pine64-Arch#498]
- Device: PinePhone
- Kernel Version : $(uname -r)
- UI: 

### Steps to reproduce
Do an update then run try to use mkimage to convert `/boot/boot.txt` to `/boot/boot.scr`.

### Expected behavior
The program to convert the `boot.txt` to `boot.scr`

### Actual behavior
libssl produces the following error
```
mkimage: error while loading shared libraries: libssdl.so.1.1: cannot open shared object file: No such file or directory
```

I believe this is due to an update to libssl and that the `uboot-tools` package needs to be rebuilt, i think thats all thats needed but im no expert.

**Comment by Danct12** [comment]
Another user having the same issue: https://archlinuxarm.org/forum/viewtopic.php?f=15&t=16247

**Comment by Danct12** [comment]
This should now be fixed upstream.
