### ISSUE TITLE
[FIXED IN DEVELOP] Call audio switching

### ISSUE THREAD

**Issue by nickgirga** [dreemurrs-embedded/Pine64-Arch#5]
Audio profiles do not automatically switch when sending or recieving calls. I had to go into settings and change "System Settings > Sound > Output > Configuration" to "Make a phone call" and the Output Device option next to it to "Internal Earpiece". Then I had to switch it back when I was done. If the switch is not done, absolutely no audio is transmitted either way, so you'd probably have to text someone that you'll call them back if they call you first because they won't be able to hear you.

(Phosh 20200629 Release on PinePhone UBports CE)

**Comment by Danct12** [comment]
I'll look for a fix after I receive my UBPorts CE, my dev phone modem isn't working.

**Comment by philmmanjaro** [comment]
We fixed that on our end by patching [wys](https://gitlab.manjaro.org/manjaro-arm/packages/community/phosh/wys).

**Comment by Danct12** [comment]
Fixed in Huong Tram Linux branch.

**Comment by Danct12** [comment]
Fixed as in 2020/07/11 image.
