### ISSUE TITLE
Back camera is not working since kernel 6.x

### ISSUE THREAD

**Issue by pinoverclock** [dreemurrs-embedded/Pine64-Arch#503]
- Device: PinePhone
- Kernel Version: 6.0.10-1-aarch64
- UI: Phosh

### Steps to reproduce:
1. Open megapixels app
2. Select back camera
3. The image keeps cycling from black to white patterns

### Expected behavior
Back camera working as prior to kernel 6.x

### Actual behavior
Back camera is not working since kernel 6.x

### Logfiles and additional information
Last tested working camera with kernel 5.18.14-1-aarch64

**Comment by Danct12** [comment]
Please check out the kernel in testing repo and see if this fixes the issue for you.

**Comment by pinoverclock** [comment]
I can confirm the issue is still present in kernel 6.1.7-1

**Comment by Danct12** [comment]
That is weird, mine is working (v1.2b). Do you have any camera turned off?

**Comment by pinoverclock** [comment]
Yes, same pinephone version, all switches in the on position. 

I decided to open the Megapixels app while follwing journald log and I found something funny
When I start the Megapixels I get:
```
Jan 24 18:54:44 pp64 kernel: ov5640 4-004c: ov5640_set_ctrl_focus: can't set focus when not powered
Jan 24 18:54:47 pp64 phosh[3465]: Startup of app 'Megapixels' with startup id: '8da32141-6f8e-41d9-8bbc-a0577e082c46' timed out
```
And I have Megapixels running but cycling from black to white patterns, but once I close it I get:
```
Jan 24 18:54:55 pp64 org.postmarketos.Megapixels.desktop[10962]: Found config file at /etc/megapixels/config/pine64,pinephone-1.2.ini
Jan 24 18:54:55 pp64 org.postmarketos.Megapixels.desktop[10962]: Adding camera rear from config
Jan 24 18:54:55 pp64 org.postmarketos.Megapixels.desktop[10962]: Adding camera front from config
Jan 24 18:54:55 pp64 org.postmarketos.Megapixels.desktop[10962]: Initialized OpenGL ES 2.0
```

I tryed it a few times with the same results
[VideoDemo link valid for 24 hours](https://www.veed.io/view/1f773088-9f5e-433d-8e11-adb658473a90?sharingWidget=true&panel=share)

**Comment by Pigpog** [comment]
I have yet to see Megapixels support 6.X (maybe im just out of touch).
Instead, I use the program `qcam` from the `libcamera-tools` package, which works very well (although it's not a great UX).
One thing to note is that if the phone ever suspends after boot up, the cameras stop working and you have to reboot.

**Comment by UltraBlackLinux** [comment]
since today's libcamera update everything works as expected for me.

**Comment by Pigpog** [comment]
The cameras have been working better than ever before for me now. I think this can be closed
