### ISSUE TITLE
Unable to use sudo after update

### ISSUE THREAD

**Issue by JKakaofanatiker** [dreemurrs-embedded/Pine64-Arch#506]
I just installed Arch and updated it. After a reboot I can't use sudo anymore. It says that a file named `libcrypto.so.1.1` is missing.

**Comment by Danct12** [comment]
Yikes, not this again. This is a upstream issue from Arch Linux ARM themselves with OpenSSL being rebuilt. :\

**Comment by Danct12** [comment]
I'm not able to reproduce the issue on a fully updated install, can you be more specific on which image and how you update it?

**Comment by DrRac27** [comment]
This can also happen if you do a partial upgrade. I had the same problem once as I didn't have enough free storage and the upgrade failed. I managed to fix it via booting from SD card and chrooting into it but if you just installed I would rather reinstall as it's easier.

**Comment by Danct12** [comment]
Reporter did not response, and it's assumed to be a partial upgrade (not supported by us) or they powered off the device while an upgrade is going on.
