### ISSUE TITLE
mobile-config-firefox-3.1.0-1 causes firefox to ignore touch screen input

### ISSUE THREAD

**Issue by dukla2000** [dreemurrs-embedded/Pine64-Arch#507]
- Device: PinePhone Pro
- Kernel Version : 6.0.10-1-danctnix
- UI: sxmo/sway

### Steps to reproduce
Installing mobile-config-firefox moves tabs to bottom of screen, but screen stops responding to touch input.
Removing mobile-config-firefox moves tabs back to top but screen responds to touch input

### Expected behavior
Touch input to work, e.g. clicking on a link

### Actual behavior
Nothing happens when touching a link

### Logfiles and additional information
can provide if necessary but think spurious.

**Comment by manner82** [comment]
Have the same issue, I recommend installing desktoplike-mobile-config-firefox from aur instead. That works for now.

https://aur.archlinux.org/packages/desktop-like-mobile-config-firefox

**Comment by dariox86** [comment]
Confirmed on regular PinePhone as well.

**Comment by Danct12** [comment]
A workaround is available in mobile-config-firefox 3.2.0-1 and is currently in danctnix-testing. Please test.

**Comment by dariox86** [comment]
It works for me, but the toolbar is now at the top.

**Comment by Danct12** [comment]
Yup, that is the workaround.

**Comment by dariox86** [comment]
OK, thank you.

**Comment by dukla2000** [comment]
Looks & works fine on my PinePhone Pro, both sxmo/sway & phosh have issue resolved.
