### ISSUE TITLE
Pacman repo not available

### ISSUE THREAD

**Issue by gianmarcogg03** [dreemurrs-embedded/Pine64-Arch#508]
When I try to update the system or install a new package it fails because a repo does not work anymore: `p64.arikawa-hi.me` returns a connection refused error.

- Device: PinePhone Pro
- Kernel Version : 5.18.14-1-danctnix
- UI: Phosh

### Steps to reproduce

1. Open the terminal;
2. Update the system or install something with pacman.

### Expected behavior

It should update or install with no issues.

### Actual behavior

It fails to connect to the `p64.arikawa-hi.me` repo (connection refused).

**Comment by i3Craig** [comment]
To add some additional information to this, it appears that the domain name `p64.arikawa-hi.me` no longer resolves to an IP address. Thus, `pacman` is unable to install updates. 

![image](https://user-images.githubusercontent.com/70919757/210138933-5ecc4ed4-7617-418f-81b4-ae14a964fa1c.png)

**Comment by Danct12** [comment]
We're aware of this issue and currently is setting up a backup mirror.

**Comment by Danct12** [comment]
Repository is now back up.

**Comment by i3Craig** [comment]
I can confirm that updates are working now. Thanks for maintaining this distro fixing this server issue quickly!
