### ISSUE TITLE
Refuses to boot if hardware switches are turned off (wifi/BT, front and back camera))

### ISSUE THREAD

**Issue by ZyxerZyxani** [dreemurrs-embedded/Pine64-Arch#509]
- Device: Pinephone Pro
- Kernel Version : $(uname -r)
- UI: Tried on all images except barebones, may affect barebones as well

### Steps to reproduce
Set hardware switches, wifi/BT, front camera, and back camera to off, then turn it off. 

### Expected behavior
Expect it to boot normally. 

### Actual behavior
The pinephone pro will afterwards refuse to boot properly. It is most likely booted since it gets hot but also I need to hold the power button for a few sec, let go and then hold it for 1 or 2 sec for it to boot again. Screen gets 0 power so it looks off. 

### Logfiles and additional information
" Send journalctl of the boot session that the error occurred. "
Impossible since it needs reboot and I can't seem to access it in the boot session it blacks out

**Comment by Danct12** [comment]
This might be the same as #418, try turn on the back camera and see if it works.

**Comment by ZyxerZyxani** [comment]
I forgot about my bug report and installed Mobian. I am gonna stick with it for now. I am closing due to the issue most likely being what you linked but I ahve not confirmed it.
