### ISSUE TITLE
No HDMI-Output working on PineTab

### ISSUE THREAD

**Issue by rakor** [dreemurrs-embedded/Pine64-Arch#51]
The output of video using HDMI is not working. Monitor does not react. Also there is no setting for displays in gnome-settings

**Comment by Danct12** [comment]
With the latest kernel update, it should work now. Still very buggy and have to plug in HDMI before booting.

![image](https://user-images.githubusercontent.com/19162768/96007039-4f044680-0e68-11eb-9eb5-c935e3a1f0fc.png)
