### ISSUE TITLE
armv7 build for package ?

### ISSUE THREAD

**Issue by rhjdvsgsgks** [dreemurrs-embedded/Pine64-Arch#513]
- Device: not pine device (some armv7 device)
- Kernel Version : any
- UI: no

### Steps to reproduce
trying to install some package from your repo

### Expected behavior
have prebuilt package for armv7 target

### Actual behavior
i need to build package by my self

### Logfiles and additional information
sorry about off topic. could you please also build package for armv7. or publish your pkgbuild to aur? your pkgbuild works fine on armv7. but now i need to build each package manually. and check update manually. which is pretty inconvenient

**Comment by Danct12** [comment]
We unfortunately do not have any ARMv7 target yet.

**Comment by Danct12** [comment]
We unfortunately do not have any ARMv7 target yet.
