### ISSUE TITLE
Rebuild mesa-git to support llvm-libs v15

### ISSUE THREAD

**Issue by langfingaz** [dreemurrs-embedded/Pine64-Arch#519]
Since some days when performing system with `pacman -Syu` updates I get the following message:

```
installing llvm-libs (15.0.7-1) breaks dependency 'llvm-libs<15' required by mesa-git
```

The locally installed package for `mesa-git` has been packaged by you. Can you please rebuild it?

**Comment by Danct12** [comment]
Hi, this package has been removed. Please install the non-git version of mesa.

The package was a relic from the past, when graphics driver from the early PinePhone days was not great and frequently require patches.

**Comment by langfingaz** [comment]
Thanks for the info!
