### ISSUE TITLE
postprocessd needs new build against libraw 0.21

### ISSUE THREAD

**Issue by dukla2000** [dreemurrs-embedded/Pine64-Arch#522]
- Device: PinePhone (OG)
- Kernel Version : 6.1.7-1-danctnix
- UI: sxmo/sway

### Steps to reproduce
take a picture with megapixels with postprocessd single/quick selected

### Expected behavior
new file in ~/Pictures

### Actual behavior
postprocess fails as it is built for libraw 0.20 whereas up to date arch has libraw 0.21

### Logfiles and additional information
nothing in journal - error message can be seen if running from command line

**Comment by Danct12** [comment]
Fixed
