### ISSUE TITLE
pkg: phosh: phosh-mobile-settings: upgrade to 0.24

### ISSUE THREAD

**Issue by mikeshenson** [dreemurrs-embedded/Pine64-Arch#525]
Please update phosh-mobile-settings to 0.24
I think this should go with #521 and #518 

https://gitlab.gnome.org/guidog/phosh-mobile-settings/-/tags

**Comment by Danct12** [comment]
We're on 0.25 now, and it's in the repo.

**Comment by mikeshenson** [comment]
Thank You!
