### ISSUE TITLE
Why cant i install it to the emmc of my pinephone pro. or how do i ido it?

### ISSUE THREAD

**Issue by Supervisor360** [dreemurrs-embedded/Pine64-Arch#533]
- Device: (PinePhone or PineTab?)
- Kernel Version : $(uname -r)
- UI:

**Comment by pentamassiv** [comment]
Of course you can. Use a search engine to find the instructions on the pine64 wiki.

It is customary to first put in some effort to find the solution yourself before opening an issue in an open-source project like this one. The volunteers here are not the paid support staff from a big company. That is probably the reason why nobody else reacted to your question for days
