### ISSUE TITLE
Megapixels crashes when taking a picture on kernel 6.2

### ISSUE THREAD

**Issue by Danct12** [dreemurrs-embedded/Pine64-Arch#540]
- Device: PinePhone and PineTab
- Kernel Version : 6.2.9-2-danctnix
- UI: all

### Steps to reproduce
Open megapixels and take a picture.

### Expected behavior
Takes a picture and save it to storage.

### Actual behavior
Crash with:
```
MPCamera: VIDIOC_STREAMON error 22, Invalid argument
MPCamera: VIDIOC_DQBUF error 22, Invalid argument
```

### Logfiles and additional information
[dmesg.txt](https://github.com/dreemurrs-embedded/Pine64-Arch/files/11240398/dmesg.txt)

App log:
```
Found config file at /usr/share/megapixels/config/pine64,pinephone-1.2.ini
Adding camera rear from config
Adding camera front from config
MPDevice: MEDIA_IOC_SETUP_LINK error 22, Invalid argument
MPDevice: MEDIA_IOC_SETUP_LINK error 22, Invalid argument
MPDevice: MEDIA_IOC_SETUP_LINK error 22, Invalid argument
Initialized OpenGL ES 2.0
MPCamera: VIDIOC_STREAMON error 22, Invalid argument
MPCamera: VIDIOC_DQBUF error 22, Invalid argument
```

**This is a upstream issue, refer to:**
- https://gitlab.com/postmarketOS/pmaports/-/issues/2060
- https://gitlab.com/postmarketOS/megapixels/-/issues/66

**Comment by arthomnix** [comment]
This has been fixed in upstream Megapixels 1.6.1
