### ISSUE TITLE
Enable keyboard power manager module

### ISSUE THREAD

**Issue by Shatur** [dreemurrs-embedded/Pine64-Arch#543]
I noticed that PinePhone keyboard does not report charging level on Arch and works on other distros. I talkied with megi about it and he noticed that the keyboard power manager is not enabled:
https://github.com/dreemurrs-embedded/Pine64-Arch/blob/accb49c7954bb67d2aacdb0be26db6d7ac8eb612/PKGBUILDS/pine64/linux-megi/config#L1731
Could you please enable it by default it?

**Comment by Danct12** [comment]
Done as a part of 6.3.0 kernel.

**Comment by PublicVoidUpdate** [comment]
Do we need to activate testing to get the 6.3 kernel?

**Comment by Danct12** [comment]
Yes.
