### ISSUE TITLE
Upstreaming?

### ISSUE THREAD

**Issue by julianfairfax** [dreemurrs-embedded/Pine64-Arch#550]
It appears that the PKGBUILDS here are for kernels, drivers, and other per-device tweaks. This is normal, and makes sense.

However, it seems that there are also PKGBUILDs for mobile Linux software, like phosh. What I find odd there is: Debian has these packages in their repos.

Is Arch against packaging software for mobile Linux in their repos, or has no upateaming effort been made?

Thank you for maintaining these packages!

**Comment by shulamy1** [comment]
yes  arch is defined for x64 only
 
 ezik

**Comment by H5117** [comment]
[Phosh](https://archlinux.org/packages/extra/x86_64/phosh/) in the repository now, along with `squeekboard`, `feedbackd` and some other packages.
