### ISSUE TITLE
gnome-calendar-mobile obsolete

### ISSUE THREAD

**Issue by pentamassiv** [dreemurrs-embedded/Pine64-Arch#556]
After updating the system gnome-calendar-mobile stopped starting. I think the package became obsolete though and can be replaced by upstream gnome-calendar. At least I don't see any issues with the UI with the current version.

**Comment by Danct12** [comment]
We had to carry [0001-gcal-window-make-it-fit-phone-screens.patch](https://github.com/dreemurrs-embedded/Pine64-Arch/blob/master/PKGBUILDS/phosh/gnome-calendar-mobile/0001-gcal-window-make-it-fit-phone-screens.patch). So until then, it'll stay.

Closing as the package has been updated for some time now.
