### ISSUE TITLE
Consider gnome-settings-daemon patch to disable sleep notification

### ISSUE THREAD

**Issue by Schmiddiii** [dreemurrs-embedded/Pine64-Arch#559]
- Device: PinePhone
- Kernel Version : 6.3.7-1-danctnix
- UI: Phosh

Currently Phosh always sends a notification if it is about to sleep. This is particulary annoying with the new Phosh 0.28 update that unblanks the screen on notifications. Phosh [recommends](https://gitlab.gnome.org/World/Phosh/phosh/-/releases#patches-that-arent-merged-upstream-yet) a [patch to gnome-settings-daemon](https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/merge_requests/285) that would allow to disable this notification. Please consider providing a patched version of gnome-settings-daemon that would disable this warning.

### Steps to reproduce

Don't touch the phone for a while, the notification will show.

### Expected behavior

No notification should show, the screen should just go dark.

### Actual behavior

The notification shows up.

### Logfiles and additional information

None.

### Workaround

Note that there exists a workaround to disable waking up the screen as noted in the [PMOS issue tracker](https://gitlab.com/postmarketOS/pmaports/-/issues/2185#workaround) and the [Phosh Wiki](https://gitlab.gnome.org/World/Phosh/phosh/-/wikis/Configuration#under-smpuriphoshnotifications):

```
gsettings set sm.puri.phosh.notifications wakeup-screen-triggers '[]'
```

**Comment by Danct12** [comment]
Done in 32336b031942a5e7d9b50ba5977a54e04e6987cb. It's also added in our gschema.
