### ISSUE TITLE
PPKB_POWER_MANAGER cannot be loaded with modproble, as not found in /lib/modules

### ISSUE THREAD

**Issue by marek-lach** [dreemurrs-embedded/Pine64-Arch#560]
- Device: PinePhone Pro
- Kernel Version : 6.3.7
- UI: phosh

### Steps to reproduce
With the hardware keyboard accessory attached, I tried to load the CONFIG_PPKB_POWER_MANAGER kernel module through `sudo modprobe` to get the keyboard charging functionality, but got an error that the module was not found in `/lib/modules` ...

### Expected behavior
The _keyboard case's kernel power manager module_ loads, if the command `sudo modproble CONFIG_PPKB_POWER_MANAGER` is executed.

### Actual behavior
The module CONFIG_PPKB_POWER_MANAGER is not found and cannot be loaded (also tried just PPKB_POWER_MANAGER, same result).

**Comment by Danct12** [comment]
The module is called `ppkb-manager`.
