### ISSUE TITLE
Night color on Plasma not working (PineTab2)

### ISSUE THREAD

**Issue by AgentSmith0** [dreemurrs-embedded/Pine64-Arch#577]
**Device info (please complete the following information)**
- Device: PineTab2
- Kernel Version : 6.4.3-danctnix1-1-pinetab2
- UI: Plasma Desktop

**Describe the bug**
Enabling night color in Plasma has no effect.

**To Reproduce**
1. Try enabling night color

**Expected behavior**
Night color turns on.

**Before submitting a bug report, please be sure that you have done the following:**
- [x] I have checked for updates (pacman -Syu) and installed the updates but the problem persisted.
- [x] I am **not** using Megi's multiboot image, which is unsupported by the developer.

**Comment by Danct12** [comment]
Looks like hardware gamma controls aren't implemented in the PT2 panel driver.
