### ISSUE TITLE
Spacebar not launching

### ISSUE THREAD

**Issue by qiu-x** [dreemurrs-embedded/Pine64-Arch#597]
- Device: PinePhone (Pro)
- Kernel Version : 6.5.7-1 danctnix
- UI: Plasma Mobile

I get the following error when attempting to launch Spacebar:
```
spacebar: symbol lookup error: spacebar: undefined symbol: _ZN4i18n12phonenumbers11PhoneNumberC1ERKS1_
```
(The problem also persisted on a clean reinstall)

When I used the PKGBUILD in the repo to build the package then Spacebar
started correctly, but I was unable to send or receive SMS messages.

Spacebar version: `23.01.0-3`

**Comment by Danct12** [comment]
Fixed in 5cd65204fc5ad263442d9b0ad871a68a9f9970d3
