### ISSUE TITLE
Telegram Desktop refuses to work if audio profile is set to voicecall

### ISSUE THREAD

**Issue by ScardracS** [dreemurrs-embedded/Pine64-Arch#6]
Not sure about other OS, but there is a bug that prevent Telegram to pass first screen if sound is set as "Make a voice call" instead of "Play HiFi". I will make further searches in order to determine if it's related by alarm (as well as other OS, if problem appears) or if is a problem of Telegram.

P.S.

I really hope this is a bug and not a Telegram "feature".

**Comment by Danct12** [comment]
Probably a bug with PulseAudio.

**Comment by prurigro** [comment]
I'm not getting this issue myself-- both output and input are set to "Make a phone call" and telegram desktop is working correctly

**Comment by Danct12** [comment]
Tested, I cannot reproduce the issue on my phone, I'll mark it as invalid now, please reopen if needed.

**Comment by ScardracS** [comment]
You can sign it as fixed
