### ISSUE TITLE
Maliit bug fixed for plasma-mobile-settings

### ISSUE THREAD

**Issue by avedor** [dreemurrs-embedded/Pine64-Arch#605]
**Device info (please complete the following information)**
- Device: PinePhonePro
- Kernel Version : 6.6.6-1-danctnix
- UI: Plasma Mobile

**Describe the bug**
In the PKGBUILD for plasma-mobile-settings is a reference to a KDE bug that was pending a fix. That bug has been closed, so the workaround in the PKGBUILD should be able to be removed.

[KDE Bug](https://bugs.kde.org/show_bug.cgi?id=435183)
[PKGBUILD reference to KDE Bug](https://github.com/dreemurrs-embedded/Pine64-Arch/blob/5be3b3f017cc6bac7aea1e651e7a5711f7abf8e3/PKGBUILDS/plasma/plasma-mobile-settings/PKGBUILD#L63)

**To Reproduce**
1. Go to [plasma-mobile-settings PKGBUILD](https://github.com/dreemurrs-embedded/Pine64-Arch/blob/5be3b3f017cc6bac7aea1e651e7a5711f7abf8e3/PKGBUILDS/plasma/plasma-mobile-settings/PKGBUILD#L63)
2. See note about KDE Upstream bug

**Expected behavior**
Removal of workaround as upstream bug has been resolved

**Before submitting a bug report, please be sure that you have done the following:**
- [x] I have checked for updates (pacman -Syu) and installed the updates but the problem persisted.
- [x] I am **not** using Megi's multiboot image, which is unsupported by the developer.

**Comment by Danct12** [comment]
Fixed in 49f54e0b6682470e73c63e9b373acbd11c329a3d
