### ISSUE TITLE
Ship `ffmpeg-v4l2-request-git`

### ISSUE THREAD

**Issue by Shatur** [dreemurrs-embedded/Pine64-Arch#608]
**Is your feature request related to a problem? Please describe.**

In order to have HW acceleration in apps like Moonlight I need to install patched version of ffmpeg from AUR: `ffmpeg-v4l2-request-git`. But it takes quite a lot of time to compile and the package [will be removed from AUR](https://aur.archlinux.org/packages/ffmpeg-v4l2-request-git#comment-954177) soon.

**Describe the solution you'd like**
I would suggest to provide this package as part of `danctnix` repo since it's quite important.

**Comment by Danct12** [comment]
Implemented in 541f4f2365c943195bd0b118463520ecbc825b7e
