### ISSUE TITLE
Gnome-Image for PineTab

### ISSUE THREAD

**Issue by rakor** [dreemurrs-embedded/Pine64-Arch#61]
Will you bring a Gnome-Image for the PineTab? Would be great as Gnome has decent touch-support, us a full working desktop and should run fine on the screensize and resolution.

**Comment by Danct12** [comment]
This is something we'll think of, but GNOME is kinda slow on the Mali 400.

**Comment by pitlochry** [comment]
What do I have to install/remove and enable/disable in order to use gnome-shell and not phosh/phoc?

I think that gnome without phosh/phoc should be usable on a screen like the pinetab (at least on the surface tablets gnome is totally usable).

**Comment by Danct12** [comment]
`sudo systemctl disable phosh` should be enough to stop phosh from starting.

Though, if you want to uninstall Phosh then run `pacman -Rscn danctnix-phosh-ui-meta`.

**Comment by Danct12** [comment]
Duplicate of https://github.com/dreemurrs-embedded/Pine64-Arch/issues/34
