### ISSUE TITLE
postprocessd needs rebuild against OpenCV 4.9

### ISSUE THREAD

**Issue by arthomnix** [dreemurrs-embedded/Pine64-Arch#623]
**Device info (please complete the following information)**
- Device: PinePhone 1.2b
- Kernel Version : 6.7.7-1-danctnix
- UI: sxmo (Wayland)

**Describe the bug**
`postprocessd` fails to load shared libraries as it is built against an older version of OpenCV than is currently in the Arch repository.

**To Reproduce**

1. Open a terminal
2. Run `postprocessd`
3. `postprocessd` fails to launch with the following error:
```
postprocessd: error while loading shared libraries: libopencv_videostab.so.408: cannot open shared object file: No such file or directory
```

In megapixels, this results in photos not saving when taken.

**Expected behavior**
`postprocessd` is able to load the OpenCV libraries correctly, and is able to post-process and save photos taken in megapixels.

**Logfiles and additional information**

`libopencv_videostab.so.409` (not `.so.408`) is present on the system, so I assume `postprocessd` needs to be rebuilt against the new version of OpenCV. As a temporary hack, `postprocessd` does work correctly if the required shared libraries are created as symlinks to the new versions.

**Before submitting a bug report, please be sure that you have done the following:**
- [x] I have checked for updates (pacman -Syu) and installed the updates but the problem persisted.
- [x] I am **not** using Megi's multiboot image, which is unsupported by the developer.

**Comment by Danct12** [comment]
Fixed in b0ef4f2484b402bdac26ed9e4d6d3e7c1fd29e61
