### ISSUE TITLE
wpa_supplicant 2.11 breaks Broadcom Wi-Fi 

### ISSUE THREAD

**Issue by maxrdz** [dreemurrs-embedded/Pine64-Arch#654]
**Device info (please complete the following information)**
- Device: PinePhone Pro
- Kernel Version : 6.9.7-1-megi-danctnix
- UI: Phosh

**Describe the bug**
Cannot connect to Wi-Fi network.

**To Reproduce**
Unknown, not sure if it was after a system upgrade.

**Logfiles and additional information**
Cannot provide logs since SSH is no available due to the issue.

**Before submitting a bug report, please be sure that you have done the following:**
- [x] I have checked for updates (pacman -Syu) and installed the updates but the problem persisted.
- [x] I am **not** using Megi's multiboot image, which is unsupported by the developer.

**Comment by maxrdz** [comment]
Running `doas systemctl status NetworkManager` shows some warns logged by netman.

Two lines seem to address the issue:
```
(wlan0): Activation: (wifi) association took too long
(wlan0): state change: config -> failed (reason 'no-secrets', sys-iface-state: 'managed')

```

**Comment by Danct12** [comment]
Add `brcmfmac.feature_disable=0x82000` to the kernel command line and wait for a fix.

**Comment by maxrdz** [comment]
> Add `brcmfmac.feature_disable=0x82000` to the kernel command line and wait for a fix.

I tried to do this by editing the GRUB configuration, which should be at `/etc/default/grub`, but no file exists on my system. Which method do you recommend to append this kernel parameter?

**Comment by maxrdz** [comment]
Oh I might be clueless. I assume GRUB is not installed on the Pinephone is it :p

**Comment by maxrdz** [comment]
> Add `brcmfmac.feature_disable=0x82000` to the kernel command line and wait for a fix.

Tried `doas sysctl brcmfmac.feature_disable=0x82000` to set it at runtime, but it says the file does not exist under `/proc/sys/...`.

**Comment by Danct12** [comment]
No, this is a kernel cmdline.

You need to edit boot.txt and run ./mkscr script in /boot.

**Comment by maxrdz** [comment]
This workaround fixed my issue, thank you!

**Comment by Danct12** [comment]
This workaround is now a part of c2b933bbc4b5c4f1bae4a869c272f6669429fe14
