### ISSUE TITLE
Remove qt6-quickcontrols2 dependency

### ISSUE THREAD

**Issue by AaronSonoran** [dreemurrs-embedded/Pine64-Arch#668]
- Device: PinePhone (Pro)
- Kernel Version : 6.11.0-1-megi-danctnix
- UI: Plasma Mobile

plasma-dialer doesn't install because qt6-quickcontrols2 is in the depends list. It should be removed because quickcontrols2 is a module of qt6-declarative now.

1. sudo pacman -S plasma-dialer 
2. See error

**Expected behavior**
It installs and works fine.

**Comment by mevisc0** [comment]
I am also experiencing this bug, so I submitted a pull request #675

**Comment by Danct12** [comment]
merged
