### ISSUE TITLE
Networking totally gone

### ISSUE THREAD

**Issue by sorry-i-am-late** [dreemurrs-embedded/Pine64-Arch#673]
- Device: PinePhone 
- Kernel Version : 6.11.1
- UI: Barebone / Phosh 

Networking is totally gone as if the hardware doesn't exist but when I boot from an sd card it works fine.  NetworkManger and ModemManager are running in the background but dont seem to be doing anything. 

This happened after I updated via chroot due to the seatd issue. It behaves like it did when the wifi chip fried on my v1.2 mainboard except this time it is also the modem and networking is fine when booting from a not up to date sd card.

**Comment by sorry-i-am-late** [comment]
Marking as closed because reinstalling 6.11.1 not via chroot seems to have fixed this issue but hopefully if anyone else encounters this issue they wont have to mess around for as long.

**Comment by Danct12** [comment]
You need to mount the /boot partition.
