### ISSUE TITLE
PineTab2 phosh UI rendering broken

### ISSUE THREAD

**Issue by k8ieone** [dreemurrs-embedded/Pine64-Arch#680]
## Device info (please complete the following information)
- Device: PineTab2
- Kernel Version : `6.11.4-danctnix1-1-pinetab2`
- UI: Phosh (0.42.0-2)

## Description
GTK4 applications don't render properly. Text and icons are missing. Some icons corrupted.

## Reproduction steps
1. Remove everything Plasma-related
2. Install `phosh` and `gnome-control-center`
3. Enable `phosh.service`
4. Try opening settings

## 
The UI should render properly.

### GNOME Settings
![Pasted image](https://github.com/user-attachments/assets/544c67cd-b7be-4d1a-b515-7faef464cbad)

### Powersupply (works, GTK3)
![Pasted image (2)](https://github.com/user-attachments/assets/ab25dd8a-cd1e-477a-825f-e8afbd61e911)

### Nautilus - Files
![Pasted image (3)](https://github.com/user-attachments/assets/b93457ea-7cd0-4f31-b335-9b15b7261fa3)

### Epiphany - GNOME Web
![Pasted image (4)](https://github.com/user-attachments/assets/e6183f14-0679-420e-9208-b21da168a9f1)

## Logfiles and additional information
I've also noticed if I let the screen turn off, it'll only come up blank - the phosh lock screen won't come up. I can still connect to the device using SSH. This doesn't always happen.

GTK3 applications seem to work fine - see the second screenshot.

- [x] I have checked for updates (pacman -Syu) and installed the updates but the problem persisted.
- [x] I am **not** using Megi's multiboot image, which is unsupported by the developer.

**Comment by Danct12** [comment]
Possibly related to #626.

Try changing `GSK_RENDERER` variable in `/etc/profile.d/gsk-renderer-gl.sh` from `ngl` to `gl`.

**Comment by k8ieone** [comment]
I updated to Phosh 0.43 yesterday and it seems like the lock screen issue seems to be gone. I can lock and unlock as I please :yum:
