### ISSUE TITLE
Battery percent from the lockscreen and charging led label:enhancement 

### ISSUE THREAD

**Issue by layo123** [dreemurrs-embedded/Pine64-Arch#77]
Hi i have been using this phone with Arch as daily driver and these are two features that i miss from other operating systems, how much work is needed to implement them? Thanks to everyone contributing to this project!

**Comment by Danct12** [comment]
For the lock screen, I suggest you open a issue requesting it on [Phosh repository](https://source.puri.sm/Librem5/phosh/-/issues)

As for the charging LED, I think I might look into that

**Comment by layo123** [comment]
Thanks!

**Comment by Danct12** [comment]
This has been added to Phosh a long while ago. Closing.
