### ISSUE TITLE
geary-mobile flows past the screen's edge, non-responsive anymore

### ISSUE THREAD

**Issue by marek-lach** [dreemurrs-embedded/Pine64-Arch#78]
Not sure what the issue is, maybe a downgrade would help?

Tested on the 2GB, 1.2 version of the PinePhone.

**Comment by Danct12** [comment]
Does this issue still persists with the latest geary?

**Comment by marek-lach** [comment]
> Does this issue still persists with the latest geary?

I am not really able to confirm either way, the PKGBUILD doesn't seem to launch at all for me, even after successful installation.
