### ISSUE TITLE
Calls app broken since 20201024 update

### ISSUE THREAD

**Issue by layo123** [dreemurrs-embedded/Pine64-Arch#80]
Today i updated the phone through pacman -Syu then fixed the repository to complete the upgrade. Afterwards i noticed that the calls app did not make any sounds(both earpiece and loudspeaker). From the settings, audio tests work fine. Is there something i can try to fix it? Thanks

**Comment by PenguinOwl** [comment]
This sounds similar to the problems I just had in #79. Try adding the danctnix (instructions on the release page) and run `sudo pacman -Suu`?

**Comment by layo123** [comment]
Will give this a try thanks
