### ISSUE TITLE
Geary does not allow to setup new account

### ISSUE THREAD

**Issue by Lin-Admin** [dreemurrs-embedded/Pine64-Arch#89]
With "alarm 5.9.3-1-danctnix #1 SMP Sat Nov 7" geary does not allow to setup free account. 
When the input mask for the email address is selected, characters tapped on the keyboard do not appear in the input field.

**Comment by Danct12** [comment]
This should now be long fixed, I tested it in Geary 40 and it works fine. Feel free to open again if this is still a issue.
