### ISSUE TITLE
led is not working anymore with notifications

### ISSUE THREAD

**Issue by kapinta** [dreemurrs-embedded/Pine64-Arch#93]
Hello all,
After a pacman update some days ago, when I receive a new message in Telegram desktop, Geary or Evolution mail clients, a message is shown in notification area, but led is not switched on anymore.
In updates before led worked fine. 
I have not found any config to enable this feature again.
Thank you!

**Comment by beckerichmika** [comment]
Pull request #92 might fix that issue once it has been pulled. Now the charging LED works again on my PinePhone.

**Comment by Danct12** [comment]
fixed with the latest update
