### ISSUE TITLE
Alsamixer settings are not stored, alsactl store neither works

### ISSUE THREAD

**Issue by kapinta** [dreemurrs-embedded/Pine64-Arch#94]
Hello all!
After changing sound settings with alsamixer, and executing alsactl store command as root, when the pinephone is restarted, all this changes are lost.
Best regards.

**Comment by juanantoniomosquera** [comment]
same issue, when i change lineout to earpiece and change again works sounds.

**Comment by jackghg** [comment]
I feel like alsa for sbcs is used as a middle-driver-layer for alsa :| I mean, there is a dozen in out channels! Once I wanted to remove pulse audio! bad idea! I hope pipewire will be better.

**Comment by kapinta** [comment]
Solved! Thank you!
